<?php

/*
 * Langues proposées aux organisations (langue principale et langues
 * supplémentaires) : toutes les langues de la norme ISO 639-1, chacune dans sa
 * propre écriture suivie de son nom en français. Fichier en UTF-8.
 *
 * L'interface de l'application n'est traduite qu'en français et en anglais
 * (translated_locales) ; les autres langues servent aux documents, aux
 * libellés de l'organisation et aux futures traductions.
 */
$languages = [
    'aa' => ['Afaraf', 'afar'],
    'ab' => ['аҧсуа бызшәа', 'abkhaze'],
    'ae' => ['avesta', 'avestique'],
    'af' => ['Afrikaans', 'afrikaans'],
    'ak' => ['Akan', 'akan'],
    'am' => ['አማርኛ', 'amharique'],
    'an' => ['aragonés', 'aragonais'],
    'ar' => ['العربية', 'arabe'],
    'as' => ['অসমীয়া', 'assamais'],
    'av' => ['авар мацӀ', 'avar'],
    'ay' => ['aymar aru', 'aymara'],
    'az' => ['azərbaycan dili', 'azéri'],
    'ba' => ['башҡорт теле', 'bachkir'],
    'be' => ['беларуская мова', 'biélorusse'],
    'bg' => ['български език', 'bulgare'],
    'bi' => ['Bislama', 'bichelamar'],
    'bm' => ['bamanankan', 'bambara'],
    'bn' => ['বাংলা', 'bengali'],
    'bo' => ['བོད་ཡིག', 'tibétain'],
    'br' => ['brezhoneg', 'breton'],
    'bs' => ['bosanski jezik', 'bosniaque'],
    'ca' => ['català', 'catalan'],
    'ce' => ['нохчийн мотт', 'tchétchène'],
    'ch' => ['Chamoru', 'chamorro'],
    'co' => ['corsu', 'corse'],
    'cr' => ['ᓀᐦᐃᔭᐍᐏᐣ', 'cri'],
    'cs' => ['čeština', 'tchèque'],
    'cu' => ['ѩзыкъ словѣньскъ', 'slavon d’église'],
    'cv' => ['чӑваш чӗлхи', 'tchouvache'],
    'cy' => ['Cymraeg', 'gallois'],
    'da' => ['dansk', 'danois'],
    'de' => ['Deutsch', 'allemand'],
    'dv' => ['ދިވެހި', 'divehi'],
    'dz' => ['རྫོང་ཁ', 'dzongkha'],
    'ee' => ['Eʋegbe', 'éwé'],
    'el' => ['Ελληνικά', 'grec'],
    'en' => ['English', 'anglais'],
    'eo' => ['Esperanto', 'espéranto'],
    'es' => ['Español', 'espagnol'],
    'et' => ['eesti keel', 'estonien'],
    'eu' => ['euskara', 'basque'],
    'fa' => ['فارسی', 'persan'],
    'ff' => ['Fulfulde', 'peul'],
    'fi' => ['suomi', 'finnois'],
    'fj' => ['vosa Vakaviti', 'fidjien'],
    'fo' => ['føroyskt', 'féroïen'],
    'fr' => ['Français', 'français'],
    'fy' => ['Frysk', 'frison occidental'],
    'ga' => ['Gaeilge', 'irlandais'],
    'gd' => ['Gàidhlig', 'gaélique écossais'],
    'gl' => ['galego', 'galicien'],
    'gn' => ['Avañe’ẽ', 'guarani'],
    'gu' => ['ગુજરાતી', 'gujarati'],
    'gv' => ['Gaelg', 'mannois'],
    'ha' => ['Hausa', 'haoussa'],
    'he' => ['עברית', 'hébreu'],
    'hi' => ['हिन्दी', 'hindi'],
    'ho' => ['Hiri Motu', 'hiri motu'],
    'hr' => ['hrvatski jezik', 'croate'],
    'ht' => ['Kreyòl ayisyen', 'créole haïtien'],
    'hu' => ['magyar', 'hongrois'],
    'hy' => ['Հայերեն', 'arménien'],
    'hz' => ['Otjiherero', 'héréro'],
    'ia' => ['Interlingua', 'interlingua'],
    'id' => ['Bahasa Indonesia', 'indonésien'],
    'ie' => ['Interlingue', 'interlingue'],
    'ig' => ['Asụsụ Igbo', 'igbo'],
    'ii' => ['ꆈꌠ꒿ Nuosuhxop', 'yi du Sichuan'],
    'ik' => ['Iñupiaq', 'inupiaq'],
    'io' => ['Ido', 'ido'],
    'is' => ['Íslenska', 'islandais'],
    'it' => ['Italiano', 'italien'],
    'iu' => ['ᐃᓄᒃᑎᑐᑦ', 'inuktitut'],
    'ja' => ['日本語', 'japonais'],
    'jv' => ['basa Jawa', 'javanais'],
    'ka' => ['ქართული', 'géorgien'],
    'kg' => ['Kikongo', 'kikongo'],
    'ki' => ['Gĩkũyũ', 'kikuyu'],
    'kj' => ['Kuanyama', 'kuanyama'],
    'kk' => ['қазақ тілі', 'kazakh'],
    'kl' => ['kalaallisut', 'groenlandais'],
    'km' => ['ខ្មែរ', 'khmer'],
    'kn' => ['ಕನ್ನಡ', 'kannada'],
    'ko' => ['한국어', 'coréen'],
    'kr' => ['Kanuri', 'kanouri'],
    'ks' => ['कश्मीरी', 'cachemiri'],
    'ku' => ['Kurdî', 'kurde'],
    'kv' => ['коми кыв', 'komi'],
    'kw' => ['Kernewek', 'cornique'],
    'ky' => ['Кыргызча', 'kirghize'],
    'la' => ['latine', 'latin'],
    'lb' => ['Lëtzebuergesch', 'luxembourgeois'],
    'lg' => ['Luganda', 'ganda'],
    'li' => ['Limburgs', 'limbourgeois'],
    'ln' => ['Lingála', 'lingala'],
    'lo' => ['ພາສາລາວ', 'lao'],
    'lt' => ['lietuvių kalba', 'lituanien'],
    'lu' => ['Kiluba', 'luba-katanga'],
    'lv' => ['latviešu valoda', 'letton'],
    'mg' => ['fiteny malagasy', 'malgache'],
    'mh' => ['Kajin M̧ajeļ', 'marshallais'],
    'mi' => ['te reo Māori', 'maori'],
    'mk' => ['македонски јазик', 'macédonien'],
    'ml' => ['മലയാളം', 'malayalam'],
    'mn' => ['Монгол хэл', 'mongol'],
    'mr' => ['मराठी', 'marathi'],
    'ms' => ['Bahasa Melayu', 'malais'],
    'mt' => ['Malti', 'maltais'],
    'my' => ['ဗမာစာ', 'birman'],
    'na' => ['Dorerin Naoero', 'nauruan'],
    'nb' => ['Norsk bokmål', 'norvégien bokmål'],
    'nd' => ['isiNdebele', 'ndébélé du Nord'],
    'ne' => ['नेपाली', 'népalais'],
    'ng' => ['Owambo', 'ndonga'],
    'nl' => ['Nederlands', 'néerlandais'],
    'nn' => ['Norsk nynorsk', 'norvégien nynorsk'],
    'no' => ['Norsk', 'norvégien'],
    'nr' => ['isiNdebele', 'ndébélé du Sud'],
    'nv' => ['Diné bizaad', 'navajo'],
    'ny' => ['chiCheŵa', 'chichewa'],
    'oc' => ['occitan', 'occitan'],
    'oj' => ['ᐊᓂᔑᓈᐯᒧᐎᓐ', 'ojibwé'],
    'om' => ['Afaan Oromoo', 'oromo'],
    'or' => ['ଓଡ଼ିଆ', 'odia'],
    'os' => ['ирон æвзаг', 'ossète'],
    'pa' => ['ਪੰਜਾਬੀ', 'pendjabi'],
    'pi' => ['पाऴि', 'pali'],
    'pl' => ['polski', 'polonais'],
    'ps' => ['پښتو', 'pachto'],
    'pt' => ['Português', 'portugais'],
    'qu' => ['Runa Simi', 'quechua'],
    'rm' => ['rumantsch grischun', 'romanche'],
    'rn' => ['Ikirundi', 'kirundi'],
    'ro' => ['Română', 'roumain'],
    'ru' => ['Русский', 'russe'],
    'rw' => ['Ikinyarwanda', 'kinyarwanda'],
    'sa' => ['संस्कृतम्', 'sanskrit'],
    'sc' => ['sardu', 'sarde'],
    'sd' => ['सिन्धी', 'sindhi'],
    'se' => ['Davvisámegiella', 'same du Nord'],
    'sg' => ['yângâ tî sängö', 'sango'],
    'si' => ['සිංහල', 'cingalais'],
    'sk' => ['slovenčina', 'slovaque'],
    'sl' => ['slovenščina', 'slovène'],
    'sm' => ['gagana fa’a Samoa', 'samoan'],
    'sn' => ['chiShona', 'shona'],
    'so' => ['Soomaaliga', 'somali'],
    'sq' => ['Shqip', 'albanais'],
    'sr' => ['српски језик', 'serbe'],
    'ss' => ['SiSwati', 'swati'],
    'st' => ['Sesotho', 'sotho du Sud'],
    'su' => ['Basa Sunda', 'soundanais'],
    'sv' => ['Svenska', 'suédois'],
    'sw' => ['Kiswahili', 'swahili'],
    'ta' => ['தமிழ்', 'tamoul'],
    'te' => ['తెలుగు', 'télougou'],
    'tg' => ['тоҷикӣ', 'tadjik'],
    'th' => ['ไทย', 'thaï'],
    'ti' => ['ትግርኛ', 'tigrigna'],
    'tk' => ['Türkmen', 'turkmène'],
    'tl' => ['Wikang Tagalog', 'tagalog'],
    'tn' => ['Setswana', 'tswana'],
    'to' => ['faka Tonga', 'tongien'],
    'tr' => ['Türkçe', 'turc'],
    'ts' => ['Xitsonga', 'tsonga'],
    'tt' => ['татар теле', 'tatar'],
    'tw' => ['Twi', 'twi'],
    'ty' => ['Reo Tahiti', 'tahitien'],
    'ug' => ['ئۇيغۇرچە', 'ouïghour'],
    'uk' => ['Українська', 'ukrainien'],
    'ur' => ['اردو', 'ourdou'],
    'uz' => ['Oʻzbek', 'ouzbek'],
    've' => ['Tshivenḓa', 'venda'],
    'vi' => ['Tiếng Việt', 'vietnamien'],
    'vo' => ['Volapük', 'volapük'],
    'wa' => ['walon', 'wallon'],
    'wo' => ['Wollof', 'wolof'],
    'xh' => ['isiXhosa', 'xhosa'],
    'yi' => ['ייִדיש', 'yiddish'],
    'yo' => ['Yorùbá', 'yoruba'],
    'za' => ['Saɯ cueŋƅ', 'zhuang'],
    'zh' => ['中文', 'chinois'],
    'zu' => ['isiZulu', 'zoulou'],
];

// Français et anglais d'abord (langues traduites de l'interface), puis ordre alphabétique du nom français.
$label = fn (array $names) => mb_strtolower($names[0]) === $names[1] ? $names[0] : $names[0].' ('.$names[1].')';
$first = ['fr' => 'Français', 'en' => 'English (anglais)'];
$others = collect($languages)->except(array_keys($first))
    ->sortBy(fn (array $names) => \Illuminate\Support\Str::ascii($names[1]))
    ->map($label)->all();

return [
    'catalog' => $first + $others,
    'translated_locales' => ['fr', 'en'],
    // Paramètres régionaux (formats de date, nombres, monnaie) : langue × pays.
    'regional_formats' => [
        'fr_FR' => 'Français (France)', 'fr_CM' => 'Français (Cameroun)', 'fr_SN' => 'Français (Sénégal)',
        'fr_CI' => 'Français (Côte d’Ivoire)', 'fr_CD' => 'Français (RD Congo)', 'fr_CG' => 'Français (Congo)',
        'fr_GA' => 'Français (Gabon)', 'fr_TD' => 'Français (Tchad)', 'fr_CF' => 'Français (Centrafrique)',
        'fr_ML' => 'Français (Mali)', 'fr_BF' => 'Français (Burkina Faso)', 'fr_NE' => 'Français (Niger)',
        'fr_GN' => 'Français (Guinée)', 'fr_BJ' => 'Français (Bénin)', 'fr_TG' => 'Français (Togo)',
        'fr_BI' => 'Français (Burundi)', 'fr_RW' => 'Français (Rwanda)', 'fr_MG' => 'Français (Madagascar)',
        'fr_DJ' => 'Français (Djibouti)', 'fr_MR' => 'Français (Mauritanie)', 'fr_HT' => 'Français (Haïti)',
        'fr_BE' => 'Français (Belgique)', 'fr_CH' => 'Français (Suisse)', 'fr_CA' => 'Français (Canada)',
        'en_US' => 'English (United States)', 'en_GB' => 'English (United Kingdom)', 'en_CM' => 'English (Cameroon)',
        'en_NG' => 'English (Nigeria)', 'en_GH' => 'English (Ghana)', 'en_KE' => 'English (Kenya)',
        'en_UG' => 'English (Uganda)', 'en_TZ' => 'English (Tanzania)', 'en_ZA' => 'English (South Africa)',
        'en_SS' => 'English (South Sudan)', 'en_LR' => 'English (Liberia)', 'en_SL' => 'English (Sierra Leone)',
        'en_ZM' => 'English (Zambia)', 'en_ZW' => 'English (Zimbabwe)', 'en_MW' => 'English (Malawi)',
        'pt_PT' => 'Português (Portugal)', 'pt_BR' => 'Português (Brasil)', 'pt_MZ' => 'Português (Moçambique)',
        'pt_AO' => 'Português (Angola)', 'pt_GW' => 'Português (Guiné-Bissau)',
        'es_ES' => 'Español (España)', 'es_GQ' => 'Español (Guinea Ecuatorial)',
        'ar_MA' => 'العربية (المغرب)', 'ar_DZ' => 'العربية (الجزائر)', 'ar_TN' => 'العربية (تونس)',
        'ar_EG' => 'العربية (مصر)', 'ar_SD' => 'العربية (السودان)', 'ar_TD' => 'العربية (تشاد)',
        'sw_KE' => 'Kiswahili (Kenya)', 'sw_TZ' => 'Kiswahili (Tanzania)', 'sw_CD' => 'Kiswahili (DRC)',
        'ha_NG' => 'Hausa (Nigeria)', 'yo_NG' => 'Yorùbá (Nigeria)', 'ig_NG' => 'Igbo (Nigeria)',
        'am_ET' => 'አማርኛ (ኢትዮጵያ)', 'so_SO' => 'Soomaali (Soomaaliya)', 'rw_RW' => 'Ikinyarwanda (Rwanda)',
        'wo_SN' => 'Wollof (Senegaal)', 'ln_CD' => 'Lingála (RDC)', 'mg_MG' => 'Malagasy (Madagasikara)',
        'de_DE' => 'Deutsch (Deutschland)', 'it_IT' => 'Italiano (Italia)', 'nl_NL' => 'Nederlands (Nederland)',
    ],
];
