@extends('layouts.portal')
@section('title','Liste standard · '.$project->name)
@section('content')
<style>.standard-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:20px}.standard-card{background:#fff;border:1px solid #e8edf3;border-radius:16px;padding:20px}.choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.choice-list{max-height:190px;overflow:auto;border:1px solid #e8edf3;border-radius:12px;padding:10px}.choice-list label{display:flex;gap:9px;padding:7px}.product-row{display:grid;grid-template-columns:30px 1fr 120px 120px;gap:12px;padding:12px;border-bottom:1px solid #e8edf3;align-items:center}@media(max-width:900px){.standard-grid{grid-template-columns:1fr}.choice-grid{grid-template-columns:1fr}.product-row{grid-template-columns:30px 1fr}}</style>
<x-app-page-header title="Liste standard du projet" :subtitle="$project->name.' · '.$project->mission->name.' · '.$project->mission->country->name" icon="format_list_bulleted"><x-slot:actions><a class="app-button app-button--secondary" href="{{ route('modules.projects') }}">Retour aux projets</a></x-slot:actions></x-app-page-header>
@if(session('status'))<div class="app-alert app-alert--success">{{ session('status') }}</div>@endif
<div class="standard-grid"><div>
@if($needsRegeneration ?? false)<div class="standard-card" role="status" style="border-color:#f5d48a;background:#fff8e6;color:#8a5a00"><strong>Liste à régénérer.</strong> La configuration médicale du projet a changé depuis la publication de la version en vigueur. La liste publiée reste appliquée tant qu’une nouvelle version n’est pas validée.</div>@endif
@if($canManage)<form class="standard-card" method="post" action="{{ route('projects.standard-list.generate',$project) }}">@csrf<h2>Configurer les recommandations</h2><p>Le contexte est prérempli depuis la <a href="{{ route('projects.medical-configuration',$project) }}">configuration médicale du projet</a> ; vous pouvez l’ajuster. Les produits proposés proviennent exclusivement des correspondances du référentiel (niveaux parents et programmes inclus).</p><div class="choice-grid"><label>Niveau de soins / Programme<select name="care_level_id"><option value="">Configuration du projet</option>@foreach($options['care_level'] as $o)<option value="{{ $o->id }}" @selected(($context['care_level_id']??null)===$o->id)>{{ str_repeat('— ', max(0, ($o->depth ?? 1) - 1)) }}{{ $o->name }}</option>@endforeach</select></label><label>Catégorie de formation sanitaire *<select name="facility_category_id" required><option value="">Sélectionner</option>@foreach($options['facility_category'] as $o)<option value="{{ $o->id }}" @selected(($context['facility_category_id']??null)===$o->id)>{{ $o->name }}</option>@endforeach</select></label><div><strong>Populations cibles</strong><div class="choice-list">@foreach($options['target_population'] as $o)<label><input type="checkbox" name="target_population_ids[]" value="{{ $o->id }}" @checked(in_array($o->id,$context['target_population_ids']??[]))>{{ $o->name }}</label>@endforeach</div></div><div><strong>Pathologies</strong><div class="choice-list">@foreach($options['pathology'] as $o)<label><input type="checkbox" name="pathology_ids[]" value="{{ $o->id }}" @checked(in_array($o->id,$context['pathology_ids']??[]))>{{ $o->name }}</label>@endforeach</div></div><div><strong>Examens de laboratoire</strong><div class="choice-list">@foreach($options['laboratory_exam'] as $o)<label><input type="checkbox" name="laboratory_exam_ids[]" value="{{ $o->id }}" @checked(in_array($o->id,$context['laboratory_exam_ids']??[]))>{{ $o->name }}</label>@endforeach</div></div></div><p><x-app-button type="submit" icon="auto_awesome">Générer les produits</x-app-button></p></form>@endif
@if($recommended->isNotEmpty())<form class="standard-card" method="post" action="{{ route('projects.standard-list.save',$project) }}">@csrf @foreach($context as $key=>$value)@if(is_array($value))@foreach($value as $item)<input type="hidden" name="{{ $key }}[]" value="{{ $item }}">@endforeach @else<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<h2>Produits recommandés</h2><div class="choice-grid"><label>Code *<input name="code" value="{{ $list?->code ?? $project->code.'_STD' }}" required></label><label>Nom *<input name="name" value="{{ $list?->name ?? 'Liste standard · '.$project->name }}" required></label></div>@foreach($recommended as $product)<label class="product-row"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" checked><strong>{{ $product->name }}</strong><span>{{ $product->strength }}</span><span>{{ $product->baseUnit?->name }}</span></label>@endforeach<p><x-app-button type="submit" icon="save">Enregistrer en brouillon</x-app-button></p></form>@endif
</div><aside class="standard-card"><h2>État de la liste</h2>@if(!$list)<p><strong>Non configurée</strong></p><p>Générez les recommandations pour créer la première version.</p>@else<p><strong>{{ $list->name }}</strong></p>@foreach($list->versions as $version)<p>Version {{ $version->version_number }} · <span class="app-badge">{{ $version->status }}</span><br>{{ $version->products->count() }} produit(s)</p>@endforeach @if($canManage && $list->versions->first()?->status==='draft')<form method="post" action="{{ route('projects.standard-list.publish',[$project,$list]) }}" onsubmit="return confirm('Valider cette version ?')">@csrf<x-app-button type="submit" variant="success" icon="check">Valider la liste</x-app-button></form>@endif @endif</aside></div>
@endsection
