<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modifier {{ $managedUser->name }} · PharmaCare</title>
<style>:root{--o:#f47a20;--s:#fff7f0;--d:#382319}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:var(--s);color:var(--d)}header{background:var(--o);padding:12px 6%;color:white;display:flex;align-items:center;gap:14px}header img{width:42px;height:42px;object-fit:cover;border-radius:50%;background:white}header a{color:white}main{max-width:850px;margin:30px auto;padding:0 20px}.card{background:white;padding:24px;border-radius:16px;box-shadow:0 10px 30px #7a350015}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}label{font-weight:700}input,select{display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #dbcabd;border-radius:9px;font:inherit}button{background:var(--o);color:white;border:0;padding:12px 16px;border-radius:9px;font-weight:700}.error{background:#fff0ee;color:#b42318;padding:12px;border-radius:9px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head>
<body><header><img src="{{ asset('images/pharmacare-logo.png') }}" alt=""><a href="{{ route('users.show',$managedUser) }}">← Fiche utilisateur</a></header><main><section class="card"><h1>Modifier l’utilisateur</h1>@if($errors->any())<p class="error">{{ $errors->first() }}</p>@endif
@php($currentRole=$managedUser->roles->first()) @php($scopeValue=($currentRole?->pivot->scope_type ?? 'platform')==='platform' ? 'platform' : ($currentRole?->pivot->scope_type.':'.$currentRole?->pivot->scope_id))
<form method="post" action="{{ route('users.update',$managedUser) }}">@csrf @method('PUT')<div class="grid">
<label>Nom complet<input name="name" value="{{ old('name',$managedUser->name) }}" required></label><label>Adresse e-mail<input name="email" type="email" value="{{ old('email',$managedUser->email) }}" required></label><label>Téléphone<input name="phone" value="{{ old('phone',$managedUser->phone) }}"></label>
<label>Rôle<select name="role_id" required>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id',$currentRole?->id)==$role->id)>{{ $role->name }}</option>@endforeach</select></label>
<label>Périmètre<select name="scope" required>@if(auth()->user()->roles()->wherePivot('scope_type','platform')->exists())<option value="platform" @selected(old('scope',$scopeValue)==='platform')>Toute la plateforme</option>@endif<optgroup label="Organisations">@foreach($organizations as $organization)<option value="organization:{{ $organization->id }}" @selected(old('scope',$scopeValue)==="organization:$organization->id")>ONG · {{ $organization->name }}</option>@endforeach</optgroup><optgroup label="Projets">@foreach($projects as $project)<option value="project:{{ $project->id }}" @selected(old('scope',$scopeValue)==="project:$project->id")>Projet · {{ $project->name }} ({{ $project->organization->name }})</option>@endforeach</optgroup><optgroup label="Formations sanitaires">@foreach($facilities as $facility)<option value="facility:{{ $facility->id }}" @selected(old('scope',$scopeValue)==="facility:$facility->id")>Structure · {{ $facility->name }}</option>@endforeach</optgroup><optgroup label="Sites">@foreach($sites as $site)<option value="site:{{ $site->id }}" @selected(old('scope',$scopeValue)==="site:$site->id")>Site · {{ $site->name }} ({{ $site->healthFacility->name }})</option>@endforeach</optgroup></select></label>
<label><input style="display:inline;width:auto" type="checkbox" name="is_active" value="1" @checked(old('is_active',$managedUser->is_active))> Compte actif</label>
</div><p><button>Enregistrer les modifications</button></p></form></section></main></body></html>
