<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $managedUser->name }} · PharmaCare</title>
<style>:root{--o:#f47a20;--s:#fff7f0;--d:#382319}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:var(--s);color:var(--d)}header{background:var(--o);padding:12px 6%;color:white;display:flex;align-items:center;gap:14px}header img{width:42px;height:42px;object-fit:cover;border-radius:50%;background:white}header a{color:white;margin-right:18px}main{max-width:900px;margin:30px auto;padding:0 20px}.card{background:white;padding:24px;border-radius:16px;margin-bottom:20px;box-shadow:0 10px 30px #7a350015}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.label{color:#78665a;font-size:13px}.value{font-weight:700}.badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#fff0e5;color:#9a4300}.active{background:#eaf8ef;color:#176b3a}.actions{display:flex;gap:10px;flex-wrap:wrap}.button,button{background:var(--o);color:white;border:0;padding:11px 15px;border-radius:9px;font-weight:700;text-decoration:none}.danger{background:#b42318}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head>
<body><header><img src="{{ asset('images/pharmacare-logo.png') }}" alt=""><a href="{{ route('dashboard') }}">← Utilisateurs</a><strong>Fiche utilisateur</strong></header><main>
@if(session('success'))<p class="card">{{ session('success') }}</p>@endif
<section class="card"><h1>{{ $managedUser->name }}</h1><p><span class="badge {{ $managedUser->is_active ? 'active' : '' }}">{{ $managedUser->is_active ? 'Compte actif' : 'Compte désactivé' }}</span></p>
<div class="grid"><div><div class="label">Identifiant</div><div class="value">{{ $managedUser->username ? '@'.$managedUser->username : 'Non renseigné' }}</div></div><div><div class="label">Adresse e-mail</div><div class="value">{{ $managedUser->email }}</div></div><div><div class="label">Téléphone</div><div class="value">{{ $managedUser->phone ?: 'Non renseigné' }}</div></div><div><div class="label">Dernière connexion</div><div class="value">{{ $managedUser->last_login_at?->format('d/m/Y H:i') ?: 'Jamais' }}</div></div><div><div class="label">Mot de passe modifié</div><div class="value">{{ $managedUser->password_changed_at?->format('d/m/Y H:i') ?: 'Non renseigné' }}</div></div></div></section>
<section class="card"><h2>Rôle et périmètre</h2>@forelse($managedUser->roles as $role)<p><strong>{{ $role->name }}</strong><br><span class="label">{{ $role->pivot->scope_type }}{{ $role->pivot->scope_id ? ' · '.$role->pivot->scope_id : '' }}</span></p><p>@foreach($role->permissions as $permission)<span class="badge">{{ $permission->name }}</span> @endforeach</p>@empty<p>Aucun rôle attribué.</p>@endforelse</section>
<section class="card"><h2>Appareils</h2>@forelse($managedUser->devices as $device)<p><strong>{{ $device->name }}</strong> · {{ $device->platform }} · {{ $device->revoked_at ? 'Révoqué' : 'Autorisé' }}</p>@empty<p>Aucun appareil enregistré.</p>@endforelse</section>
<div class="actions"><a class="button" href="{{ route('users.edit',$managedUser) }}">Modifier</a><form method="post" action="{{ route('users.reset-password',$managedUser) }}">@csrf<button>Réinitialiser le mot de passe</button></form><form method="post" action="{{ route('users.destroy',$managedUser) }}" onsubmit="return confirm('Archiver définitivement ce compte ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>
</main></body></html>
