<?php

use App\Http\Controllers\Api\V1\AuditController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CatalogController;
use App\Http\Controllers\Api\V1\ConfigurationWorkflowController;
use App\Http\Controllers\Api\V1\CountryController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\DeviceController;
use App\Http\Controllers\Api\V1\DispensationController;
use App\Http\Controllers\Api\V1\EffectiveConfigurationController;
use App\Http\Controllers\Api\V1\FundingController;
use App\Http\Controllers\Api\V1\InventoryController;
use App\Http\Controllers\Api\V1\MissionController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OrganizationController;
use App\Http\Controllers\Api\V1\OperationalReportController;
use App\Http\Controllers\Api\V1\PasswordController;
use App\Http\Controllers\Api\V1\PasswordResetController;
use App\Http\Controllers\Api\V1\PlatformConfigurationController;
use App\Http\Controllers\Api\V1\ProjectController;
use App\Http\Controllers\Api\V1\ProjectStandardListController;
use App\Http\Controllers\Api\V1\ReceiptController;
use App\Http\Controllers\Api\V1\RoleController;
use App\Http\Controllers\Api\V1\StockController;
use App\Http\Controllers\Api\V1\StructureController;
use App\Http\Controllers\Api\V1\SupplyOrderController;
use App\Http\Controllers\Api\V1\UserController;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', fn (): JsonResponse => response()->json(['service' => 'sagastock-api', 'status' => 'ok', 'version' => 'v1']))->name('api.v1.health');
    Route::middleware('throttle:6,1')->group(function () {
        Route::post('/auth/login', [AuthController::class, 'login']);
        Route::post('/auth/forgot-password', [PasswordResetController::class, 'forgot']);
        Route::post('/auth/reset-password', [PasswordResetController::class, 'reset']);
    });
    Route::middleware(['auth:sanctum', 'idempotency'])->group(function (): void {
        Route::get('/configuration/effective', [EffectiveConfigurationController::class, 'index']);
        Route::post('/configuration/effective/acknowledge', [EffectiveConfigurationController::class, 'acknowledge']);
        Route::get('/configuration/workflows', [ConfigurationWorkflowController::class, 'index'])->middleware('permission:configuration.view');
        Route::post('/configuration/workflows', [ConfigurationWorkflowController::class, 'store'])->middleware('permission:configuration.view');
        Route::get('/configuration/workflows/{workflow}', [ConfigurationWorkflowController::class, 'show'])->middleware('permission:configuration.view');
        Route::put('/configuration/workflows/{workflow}/draft', [ConfigurationWorkflowController::class, 'draft'])->middleware('permission:configuration.view');
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::post('/notifications/read-all', [NotificationController::class, 'readAll']);
        Route::post('/notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::get('/organizations/{organization}/operational-report', [OperationalReportController::class, 'index']);
        Route::get('/projects/medical-references', [\App\Http\Controllers\Api\V1\MedicalReferenceController::class, 'show'])->middleware('permission:standard_lists.view');
        Route::post('/projects/medical-references/care-levels', [\App\Http\Controllers\Api\V1\MedicalReferenceController::class, 'storeCareLevel'])->middleware('permission:standard_lists.manage');
        Route::delete('/projects/medical-references/care-levels/{reference}', [\App\Http\Controllers\Api\V1\MedicalReferenceController::class, 'archiveCareLevel'])->middleware('permission:standard_lists.manage');
        Route::post('/projects/medical-references/{type}', [\App\Http\Controllers\Api\V1\MedicalReferenceController::class, 'storeReference'])->whereIn('type', ['target_population', 'pathology'])->middleware('permission:standard_lists.manage');
        Route::get('/projects/{project}/medical-configuration', [\App\Http\Controllers\Api\V1\ProjectMedicalConfigurationController::class, 'show'])->middleware('permission:projects.view');
        Route::put('/projects/{project}/medical-configuration', [\App\Http\Controllers\Api\V1\ProjectMedicalConfigurationController::class, 'update'])->middleware('permission:standard_lists.manage');
        Route::get('/projects/{project}', [ProjectController::class, 'show'])->middleware('permission:projects.view');
        Route::middleware(['role:sago_admin', 'permission:platform_standards.view'])->prefix('platform-configuration')->group(function (): void {
            Route::get('/', [PlatformConfigurationController::class, 'home']);
            Route::get('/organizations', [PlatformConfigurationController::class, 'organizations']);
            Route::get('/organizations/{organization}', [PlatformConfigurationController::class, 'organization']);
            Route::post('/organizations/{organization}/preview', [PlatformConfigurationController::class, 'preview'])->middleware('permission:standards.assign');
            Route::post('/organizations/{organization}/apply', [PlatformConfigurationController::class, 'apply'])->middleware('permission:standards.assign');
            Route::get('/history', [PlatformConfigurationController::class, 'history']);
        });
        Route::middleware('permission:stocks.view')->group(function (): void {
            Route::get('/organizations/{organization}/stocks/balances', [StockController::class, 'balances']);
            Route::get('/organizations/{organization}/stocks/movements', [StockController::class, 'movements']);
            Route::get('/organizations/{organization}/stocks/fefo', [StockController::class, 'fefo']);
            Route::get('/organizations/{organization}/stocks/transfers', [StockController::class, 'transfers']);
            Route::get('/organizations/{organization}/stocks/holds', [StockController::class, 'holds']);
        });
        Route::middleware('permission:stocks.manage')->group(function (): void {
            Route::get('/organizations/{organization}/stocks/options', [StockController::class, 'options']);
            Route::post('/organizations/{organization}/stocks/movements', [StockController::class, 'storeMovement']);
        });
        Route::middleware('permission:stocks.adjust')->group(function (): void {
            Route::post('/organizations/{organization}/stocks/movements/{movement}/compensate', [StockController::class, 'compensate']);
            Route::post('/organizations/{organization}/stocks/holds', [StockController::class, 'storeHold']);
            Route::post('/organizations/{organization}/stocks/holds/{hold}/release', [StockController::class, 'releaseHold']);
        });
        Route::middleware('permission:transfers.manage')->group(function (): void {
            Route::post('/organizations/{organization}/stocks/transfers', [StockController::class, 'storeTransfer']);
            Route::post('/organizations/{organization}/stocks/transfers/{transfer}/dispatch', [StockController::class, 'dispatch']);
            Route::post('/organizations/{organization}/stocks/transfers/{transfer}/receive', [StockController::class, 'receive']);
        });
        Route::get('/organizations/{organization}/inventories', [InventoryController::class, 'index'])->middleware('permission:inventories.view');
        Route::middleware('permission:inventories.manage')->group(function (): void {
            Route::get('/organizations/{organization}/inventories/options', [InventoryController::class, 'options']);
            Route::post('/organizations/{organization}/inventories', [InventoryController::class, 'store']);
            Route::post('/organizations/{organization}/inventories/{inventory}/start', [InventoryController::class, 'start']);
            Route::put('/organizations/{organization}/inventories/{inventory}/count', [InventoryController::class, 'count']);
            Route::post('/organizations/{organization}/inventories/{inventory}/submit', [InventoryController::class, 'submit']);
        });
        Route::post('/organizations/{organization}/inventories/{inventory}/validate', [InventoryController::class, 'validateInventory'])->middleware('permission:inventories.validate');
        Route::get('/organizations/{organization}/orders', [SupplyOrderController::class, 'index'])->middleware('permission:orders.view');
        Route::middleware('permission:orders.manage')->group(function (): void {
            Route::get('/organizations/{organization}/orders/options', [SupplyOrderController::class, 'options']);
            Route::post('/organizations/{organization}/orders', [SupplyOrderController::class, 'store']);
            Route::post('/organizations/{organization}/orders/{order}/submit', [SupplyOrderController::class, 'submit']);
        });
        Route::post('/organizations/{organization}/orders/{order}/decision', [SupplyOrderController::class, 'decide'])->middleware('permission:orders.approve');
        Route::post('/organizations/{organization}/orders/{order}/prepare', [SupplyOrderController::class, 'prepare'])->middleware('permission:orders.prepare');
        Route::get('/organizations/{organization}/receipts', [ReceiptController::class, 'index'])->middleware('permission:stocks.view');
        Route::middleware('permission:receipts.manage')->group(function (): void {
            Route::get('/organizations/{organization}/receipts/options', [ReceiptController::class, 'options']);
            Route::post('/organizations/{organization}/receipts', [ReceiptController::class, 'store']);
            Route::post('/organizations/{organization}/receipts/{receipt}/validate', [ReceiptController::class, 'validateReceipt']);
        });
        Route::get('/organizations/{organization}/patients', [DispensationController::class, 'patients'])->middleware('permission:patients.view');
        Route::get('/organizations/{organization}/patients/{patient}/history', [DispensationController::class, 'patientHistory'])->middleware('permission:patients.view');
        Route::middleware('permission:patients.manage')->group(function (): void {
            Route::post('/organizations/{organization}/patients', [DispensationController::class, 'storePatient']);
            Route::put('/organizations/{organization}/patients/{patient}', [DispensationController::class, 'updatePatient']);
            Route::delete('/organizations/{organization}/patients/{patient}', [DispensationController::class, 'archivePatient']);
            Route::post('/organizations/{organization}/patients/archived/{patient}/restore', [DispensationController::class, 'restorePatient']);
        });
        Route::get('/organizations/{organization}/prescriptions', [DispensationController::class, 'prescriptions'])->middleware('permission:prescriptions.view');
        Route::post('/organizations/{organization}/prescriptions', [DispensationController::class, 'storePrescription'])->middleware('permission:prescriptions.manage');
        Route::post('/organizations/{organization}/prescriptions/{prescription}/validate', [DispensationController::class, 'validatePrescription'])->middleware('permission:prescriptions.validate');
        Route::get('/organizations/{organization}/dispensations', [DispensationController::class, 'dispensations'])->middleware('permission:dispensations.view');
        Route::middleware('permission:dispensations.manage')->group(function (): void {
            Route::get('/organizations/{organization}/dispensations/options', [DispensationController::class, 'options']);
            Route::get('/organizations/{organization}/dispensations/fefo', [DispensationController::class, 'fefoSuggestion']);
            Route::post('/organizations/{organization}/dispensations', [DispensationController::class, 'storeDispensation']);
            Route::post('/organizations/{organization}/dispensations/{dispensation}/return', [DispensationController::class, 'returnDispensation']);
        });
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::put('/auth/locale', [AuthController::class, 'updateLocale']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::put('/auth/password', [PasswordController::class, 'update']);
        Route::get('/auth/devices', [DeviceController::class, 'index']);
        Route::delete('/auth/devices/{device}', [DeviceController::class, 'revoke']);
        Route::get('/roles', [UserController::class, 'roles'])->middleware('permission:users.view');
        Route::get('/assignable-roles', [UserController::class, 'assignableRoles']);
        Route::get('/security/roles', [RoleController::class, 'index'])->middleware('permission:roles.manage');
        Route::post('/security/roles', [RoleController::class, 'store'])->middleware('permission:roles.manage');
        Route::put('/security/roles/{role}', [RoleController::class, 'update'])->middleware('permission:roles.manage');
        Route::delete('/security/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:roles.manage');
        Route::get('/security/audits', [AuditController::class, 'index'])->middleware('permission:audit.view');
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:users.view');
        Route::get('/users/archived', [UserController::class, 'archived'])->middleware('permission:users.view');
        Route::get('/users/archived/{user}', [UserController::class, 'showArchived'])->middleware('permission:users.view');
        Route::post('/users/archived/{user}/restore', [UserController::class, 'restore'])->middleware('permission:users.manage');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:users.manage|users.create_site_admin');
        Route::get('/users/{user}', [UserController::class, 'show'])->middleware('permission:users.view');
        Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:users.manage|users.update_site_admin');
        Route::delete('/users/{user}', [UserController::class, 'destroy'])->middleware('permission:users.manage|users.suspend_site_admin');
        Route::post('/users/{user}/reset-password', [UserController::class, 'resetPassword'])->middleware('permission:users.manage|users.update_site_admin');
        Route::get('/organizations', [OrganizationController::class, 'index'])->middleware('permission:organizations.view');
        Route::get('/organizations/archived', [OrganizationController::class, 'archived'])->middleware('permission:organizations.view');
        Route::post('/organizations/archived/{organization}/restore', [OrganizationController::class, 'restore'])->middleware('permission:organizations.manage');
        Route::get('/organizations/{organization}', [OrganizationController::class, 'show'])->middleware('permission:organizations.view');
        Route::post('/organizations', [OrganizationController::class, 'store'])->middleware('permission:organizations.manage');
        Route::put('/organizations/{organization}', [OrganizationController::class, 'update'])->middleware('permission:organizations.manage');
        Route::delete('/organizations/{organization}', [OrganizationController::class, 'destroy'])->middleware('permission:organizations.manage');
        Route::get('/countries', [CountryController::class, 'index'])
            ->middleware('permission:organizations.manage|missions.view');
        Route::get('/organizations/{organization}/missions', [MissionController::class, 'index'])->middleware('permission:missions.view');
        Route::get('/organizations/{organization}/missions-archived', [MissionController::class, 'archived'])->middleware('permission:missions.view');
        Route::post('/organizations/{organization}/missions', [MissionController::class, 'store'])->middleware('permission:missions.manage');
        Route::put('/organizations/{organization}/missions/{mission}', [MissionController::class, 'update'])->middleware('permission:missions.manage');
        Route::delete('/organizations/{organization}/missions/{mission}', [MissionController::class, 'destroy'])->middleware('permission:missions.manage');
        Route::post('/organizations/{organization}/missions/archived/{mission}/restore', [MissionController::class, 'restore'])->middleware('permission:missions.manage');
        Route::get('/organizations/{organization}/projects', [ProjectController::class, 'index'])->middleware('permission:projects.view');
        Route::get('/organizations/{organization}/projects-setup', [ProjectController::class, 'setup'])->middleware('permission:projects.view');
        Route::get('/organizations/{organization}/projects/archived', [ProjectController::class, 'archived'])->middleware('permission:projects.view');
        Route::post('/organizations/{organization}/projects', [ProjectController::class, 'store'])->middleware('permission:projects.manage');
        Route::put('/organizations/{organization}/projects/{project}', [ProjectController::class, 'update'])->middleware('permission:projects.manage');
        Route::delete('/organizations/{organization}/projects/{project}', [ProjectController::class, 'destroy'])->middleware('permission:projects.manage');
        Route::post('/organizations/{organization}/projects/archived/{project}/restore', [ProjectController::class, 'restore'])->middleware('permission:projects.manage');
        Route::get('/organizations/{organization}/projects/{project}/funding', [FundingController::class, 'index'])->middleware('permission:funding.view');
        Route::post('/organizations/{organization}/donors', [FundingController::class, 'storeDonor'])->middleware('permission:funding.manage');
        Route::post('/organizations/{organization}/programs', [FundingController::class, 'storeProgram'])->middleware('permission:funding.manage');
        Route::put('/organizations/{organization}/donors/{donor}', [FundingController::class, 'updateDonor'])->middleware('permission:funding.manage');
        Route::delete('/organizations/{organization}/donors/{donor}', [FundingController::class, 'archiveDonor'])->middleware('permission:funding.manage');
        Route::post('/organizations/{organization}/donors/archived/{donor}/restore', [FundingController::class, 'restoreDonor'])->middleware('permission:funding.manage');
        Route::put('/organizations/{organization}/programs/{program}', [FundingController::class, 'updateProgram'])->middleware('permission:funding.manage');
        Route::delete('/organizations/{organization}/programs/{program}', [FundingController::class, 'archiveProgram'])->middleware('permission:funding.manage');
        Route::post('/organizations/{organization}/programs/archived/{program}/restore', [FundingController::class, 'restoreProgram'])->middleware('permission:funding.manage');
        Route::post('/organizations/{organization}/projects/{project}/donors', [FundingController::class, 'attachDonor'])->middleware('permission:funding.manage');
        Route::post('/organizations/{organization}/projects/{project}/programs', [FundingController::class, 'attachProgram'])->middleware('permission:funding.manage');
        Route::delete('/organizations/{organization}/projects/{project}/donors/{donor}', [FundingController::class, 'detachDonor'])->middleware('permission:funding.manage');
        Route::delete('/organizations/{organization}/projects/{project}/programs/{program}', [FundingController::class, 'detachProgram'])->middleware('permission:funding.manage');
        Route::get('/organizations/{organization}/structures', [StructureController::class, 'index'])->middleware('permission:structures.view|health_facilities.view');
        Route::post('/organizations/{organization}/facilities', [StructureController::class, 'storeFacility'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::get('/organizations/{organization}/facilities/{facility}', [StructureController::class, 'showFacility'])->middleware('permission:structures.view|health_facilities.view');
        Route::put('/organizations/{organization}/facilities/{facility}', [StructureController::class, 'updateFacility'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::delete('/organizations/{organization}/facilities/{facility}', [StructureController::class, 'archiveFacility'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/archived/{facility}/restore', [StructureController::class, 'restoreFacility'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/departments', [StructureController::class, 'storeDepartment'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::put('/organizations/{organization}/facilities/{facility}/departments/{department}', [StructureController::class, 'updateDepartment'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::delete('/organizations/{organization}/facilities/{facility}/departments/{department}', [StructureController::class, 'archiveDepartment'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/departments/archived/{department}/restore', [StructureController::class, 'restoreDepartment'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/pharmacies', [StructureController::class, 'storePharmacy'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::put('/organizations/{organization}/facilities/{facility}/pharmacies/{pharmacy}', [StructureController::class, 'updatePharmacy'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::delete('/organizations/{organization}/facilities/{facility}/pharmacies/{pharmacy}', [StructureController::class, 'archivePharmacy'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/pharmacies/archived/{pharmacy}/restore', [StructureController::class, 'restorePharmacy'])->middleware('permission:structures.manage|health_facilities.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/sites', [StructureController::class, 'storeSite'])->middleware('permission:structures.manage|dispensing_sites.manage');
        Route::get('/organizations/{organization}/facilities/{facility}/sites/{site}', [StructureController::class, 'showSite'])->middleware('permission:structures.view|dispensing_sites.view');
        Route::put('/organizations/{organization}/facilities/{facility}/sites/{site}', [StructureController::class, 'updateSite'])->middleware('permission:structures.manage|dispensing_sites.manage');
        Route::delete('/organizations/{organization}/facilities/{facility}/sites/{site}', [StructureController::class, 'archiveSite'])->middleware('permission:structures.manage|dispensing_sites.manage');
        Route::post('/organizations/{organization}/facilities/{facility}/sites/archived/{site}/restore', [StructureController::class, 'restoreSite'])->middleware('permission:structures.manage|dispensing_sites.manage');
        Route::put('/organizations/{organization}/module-activations', [StructureController::class, 'activation'])->middleware('permission:modules.manage');
        Route::get('/organizations/{organization}/catalog/references', [CatalogController::class, 'references'])->middleware('permission:catalog.view');
        Route::get('/organizations/{organization}/catalog/references/care-level-tree', [CatalogController::class, 'careLevelTree'])->middleware('permission:catalog.view|standard_lists.view');
        Route::post('/organizations/{organization}/catalog/references', [CatalogController::class, 'storeReference'])->middleware('permission:catalog.manage');
        Route::put('/organizations/{organization}/catalog/references/{reference}', [CatalogController::class, 'updateReference'])->middleware('permission:catalog.manage');
        Route::delete('/organizations/{organization}/catalog/references/{reference}', [CatalogController::class, 'archiveReference'])->middleware('permission:catalog.manage');
        Route::post('/organizations/{organization}/catalog/references/archived/{reference}/restore', [CatalogController::class, 'restoreReference'])->middleware('permission:catalog.manage');
        Route::get('/organizations/{organization}/catalog/suppliers', [CatalogController::class, 'suppliers'])->middleware('permission:catalog.view');
        Route::post('/organizations/{organization}/catalog/suppliers', [CatalogController::class, 'storeSupplier'])->middleware('permission:catalog.manage');
        Route::put('/organizations/{organization}/catalog/suppliers/{supplier}', [CatalogController::class, 'updateSupplier'])->middleware('permission:catalog.manage');
        Route::delete('/organizations/{organization}/catalog/suppliers/{supplier}', [CatalogController::class, 'archiveSupplier'])->middleware('permission:catalog.manage');
        Route::post('/organizations/{organization}/catalog/suppliers/archived/{supplier}/restore', [CatalogController::class, 'restoreSupplier'])->middleware('permission:catalog.manage');
        Route::get('/organizations/{organization}/catalog/products', [CatalogController::class, 'products'])->middleware('permission:catalog.view');
        Route::post('/organizations/{organization}/catalog/products', [CatalogController::class, 'storeProduct'])->middleware('permission:products.manage|catalog.manage');
        Route::put('/organizations/{organization}/catalog/products/{product}', [CatalogController::class, 'updateProduct'])->middleware('permission:products.manage|catalog.manage');
        Route::delete('/organizations/{organization}/catalog/products/{product}', [CatalogController::class, 'archiveProduct'])->middleware('permission:products.manage|catalog.manage');
        Route::post('/organizations/{organization}/catalog/products/archived/{product}/restore', [CatalogController::class, 'restoreProduct'])->middleware('permission:products.manage|catalog.manage');
        Route::get('/organizations/{organization}/catalog/batches', [CatalogController::class, 'batches'])->middleware('permission:catalog.view');
        Route::post('/organizations/{organization}/catalog/batches', [CatalogController::class, 'storeBatch'])->middleware('permission:batches.manage');
        Route::put('/organizations/{organization}/catalog/batches/{batch}', [CatalogController::class, 'updateBatch'])->middleware('permission:batches.manage');
        Route::delete('/organizations/{organization}/catalog/batches/{batch}', [CatalogController::class, 'archiveBatch'])->middleware('permission:batches.manage');
        Route::post('/organizations/{organization}/catalog/batches/archived/{batch}/restore', [CatalogController::class, 'restoreBatch'])->middleware('permission:batches.manage');
        Route::post('/organizations/{organization}/catalog/kits', [CatalogController::class, 'storeKit'])->middleware('permission:catalog.manage');
        Route::put('/organizations/{organization}/catalog/kits/{kit}', [CatalogController::class, 'updateKit'])->middleware('permission:catalog.manage');
        Route::delete('/organizations/{organization}/catalog/kits/{kit}', [CatalogController::class, 'archiveKit'])->middleware('permission:catalog.manage');
        Route::post('/organizations/{organization}/catalog/kits/archived/{kit}/restore', [CatalogController::class, 'restoreKit'])->middleware('permission:catalog.manage');
        Route::get('/organizations/{organization}/catalog/lists', [CatalogController::class, 'lists'])->middleware('permission:catalog.view');
        Route::post('/organizations/{organization}/catalog/lists', [CatalogController::class, 'storeList'])->middleware('permission:standard_lists.manage|catalog.manage');
        Route::put('/organizations/{organization}/catalog/lists/{standardList}', [CatalogController::class, 'updateList'])->middleware('permission:standard_lists.manage|catalog.manage');
        Route::delete('/organizations/{organization}/catalog/lists/{standardList}', [CatalogController::class, 'archiveList'])->middleware('permission:standard_lists.manage|catalog.manage');
        Route::post('/organizations/{organization}/catalog/lists/archived/{standardList}/restore', [CatalogController::class, 'restoreList'])->middleware('permission:standard_lists.manage|catalog.manage');
        Route::post('/organizations/{organization}/catalog/lists/{standardList}/versions', [CatalogController::class, 'newListVersion'])->middleware('permission:standard_lists.manage|catalog.manage');
        Route::post('/organizations/{organization}/catalog/lists/{standardList}/versions/{version}/publish', [CatalogController::class, 'publishListVersion'])->middleware('permission:catalog.publish');
        Route::get('/projects/{project}/standard-list', [ProjectStandardListController::class, 'show'])->middleware('permission:standard_lists.view');
        Route::post('/projects/{project}/standard-list/generate', [ProjectStandardListController::class, 'generate'])->middleware('permission:standard_lists.manage');
        Route::post('/projects/{project}/standard-list', [ProjectStandardListController::class, 'save'])->middleware('permission:standard_lists.manage');
        Route::post('/projects/{project}/standard-list/{list}/publish', [ProjectStandardListController::class, 'publish'])->middleware('permission:standard_lists.manage');
        Route::put('/projects/{project}/standard-list/products/{product}/mappings', [ProjectStandardListController::class, 'mapProduct'])->middleware('permission:standard_lists.manage');
    });
});
