@php($values = (array) ($category['current']?->configuration['definition'] ?? []))
@if($key === 'general')
    <label class="oa-field"><span>Fuseau horaire *</span><select name="settings[timezone]" required>@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(($values['timezone'] ?? 'Africa/Douala') === $timezone)>{{ $timezone }}</option>@endforeach</select></label>
    <label class="oa-field"><span>Paramètres régionaux *</span><select name="settings[locale]" required>@foreach(config('pharmacare_languages.regional_formats', []) as $code=>$label)<option value="{{ $code }}" @selected(($values['locale'] ?? 'fr_FR') === $code)>{{ $label }}</option>@endforeach</select></label>
    <label class="oa-field"><span>Format de date *</span><select name="settings[date_format]" required>@foreach(['d/m/Y'=>'31/12/2026','Y-m-d'=>'2026-12-31','m/d/Y'=>'12/31/2026'] as $code=>$label)<option value="{{ $code }}" @selected(($values['date_format'] ?? 'd/m/Y') === $code)>{{ $label }}</option>@endforeach</select></label>
    <label class="oa-field"><span>Format de l’heure *</span><select name="settings[time_format]" required><option value="H:i" @selected(($values['time_format'] ?? 'H:i') === 'H:i')>24 heures</option><option value="h:i A" @selected(($values['time_format'] ?? '') === 'h:i A')>12 heures</option></select></label>
@elseif($key === 'access')
    <fieldset class="oa-options"><legend>Profils standards autorisés *</legend>@foreach(['ADMIN_COORDINATION'=>'Admin Coordination','ADMIN_PROJECT'=>'Admin Projet','ADMIN_SITE'=>'Admin Site'] as $code=>$label)<label><input type="checkbox" name="settings[allowed_profiles][]" value="{{ $code }}" @checked(in_array($code, $values['allowed_profiles'] ?? ['ADMIN_COORDINATION','ADMIN_PROJECT','ADMIN_SITE'], true))>{{ $label }}</label>@endforeach</fieldset>
    <div class="oa-sheet-warning"><span class="material-symbols-outlined">verified_user</span>Cette politique configure uniquement les profils standards. Aucun compte utilisateur, mot de passe ou donnée personnelle n’est accessible ici.</div>
@elseif($key === 'security')
    <label class="oa-field"><span>Durée de session (minutes) *</span><input type="number" name="settings[session_duration_minutes]" min="5" max="1440" value="{{ $values['session_duration_minutes'] ?? 60 }}" required></label>
    <label class="oa-switch"><input type="hidden" name="settings[logout_after_inactivity]" value="0"><input type="checkbox" name="settings[logout_after_inactivity]" value="1" @checked($values['logout_after_inactivity'] ?? true)><span>Déconnexion après inactivité</span></label>
    <label class="oa-field"><span>Nombre maximal de tentatives *</span><input type="number" name="settings[maximum_login_attempts]" min="1" max="20" value="{{ $values['maximum_login_attempts'] ?? 5 }}" required></label>
    <label class="oa-field"><span>Verrouillage temporaire (minutes) *</span><input type="number" name="settings[temporary_lock_minutes]" min="1" max="1440" value="{{ $values['temporary_lock_minutes'] ?? 15 }}" required></label>
    <label class="oa-field"><span>Politique d’authentification *</span><select name="settings[authentication_policy]" required><option value="standard" @selected(($values['authentication_policy'] ?? 'standard') === 'standard')>Standard</option><option value="strict" @selected(($values['authentication_policy'] ?? '') === 'strict')>Renforcée</option></select></label>
@elseif($key === 'synchronization')
    @foreach(['automatic_sync'=>'Synchronisation automatique','sync_on_reconnect'=>'Synchronisation au retour du réseau','offline_enabled'=>'Fonctionnement hors connexion'] as $name=>$label)<label class="oa-switch"><input type="hidden" name="settings[{{ $name }}]" value="0"><input type="checkbox" name="settings[{{ $name }}]" value="1" @checked($values[$name] ?? true)><span>{{ $label }}</span></label>@endforeach
    <label class="oa-field"><span>Téléchargement des configurations *</span><select name="settings[configuration_download]" required><option value="automatic" @selected(($values['configuration_download'] ?? 'automatic') === 'automatic')>Automatique</option><option value="manual" @selected(($values['configuration_download'] ?? '') === 'manual')>Manuel</option></select></label>
    <label class="oa-field"><span>Intervalle de synchronisation (minutes) *</span><input type="number" name="settings[sync_interval_minutes]" min="5" max="1440" value="{{ $values['sync_interval_minutes'] ?? 15 }}" required></label>
@else
    @foreach(['notifications_enabled'=>'Notifications de plateforme','maintenance_messages'=>'Messages de maintenance','support_contact_visible'=>'Contact support visible'] as $name=>$label)<label class="oa-switch"><input type="hidden" name="settings[{{ $name }}]" value="0"><input type="checkbox" name="settings[{{ $name }}]" value="1" @checked($values[$name] ?? true)><span>{{ $label }}</span></label>@endforeach
    <label class="oa-field"><span>Taille des listes par défaut *</span><select name="settings[default_page_size]" required>@foreach([10,25,50] as $size)<option value="{{ $size }}" @selected((int)($values['default_page_size'] ?? 25) === $size)>{{ $size }} éléments</option>@endforeach</select></label>
@endif
