@extends('layouts.portal')
@section('title','Tableau de bord · PharmaCare')
@section('page-title','Tableau de bord')
@section('hide-breadcrumb','1')
@section('content')
@php($categoryLabels=['general'=>'Général','access'=>'Accès & rôles','security'=>'Sécurité','synchronization'=>'Synchronisation','platform'=>'Paramètres plateforme'])
<main class="sd-page">
 <header class="sd-head"><h1>Bienvenue, {{ auth()->user()->first_name ?: auth()->user()->name }}</h1><p>Vue d’ensemble globale de la plateforme PharmaCare.</p></header>
 <section class="sd-kpis">
  @foreach([
   ['domain',$sagoStats['organizations_total'],'Organisations enregistrées','blue',route('configuration.organization')],
   ['verified_user',$sagoStats['active'],'Organisations actives','green',route('configuration.organization',['status'=>'active'])],
   ['history',$sagoStats['interventions'],'Interventions','purple',route('configuration.platform-standards.index',['tab'=>'history'])],
   ['sync',$sagoStats['pending_sync'],'En attente de synchronisation','orange',route('configuration.platform-standards.index',['tab'=>'history','history_status'=>'pending'])],
   ['shield',$sagoStats['compliance'].'%','Taux global de conformité','navy',route('configuration.platform-standards.index')]
  ] as [$icon,$value,$label,$tone,$url])<a href="{{ $url }}" class="{{ $tone }}"><i class="material-symbols-outlined">{{ $icon }}</i><strong>{{ $value }}</strong><span>{{ $label }}</span><small>Voir les détails →</small></a>@endforeach
 </section>
 <div class="sd-grid"><section class="sd-card"><header><h2>Activités récentes</h2><a href="{{ route('configuration.platform-standards.index',['tab'=>'history']) }}">Voir tout</a></header><div class="sd-table"><table><thead><tr><th>Organisation</th><th>Intervention</th><th>Catégorie</th><th>Auteur</th><th>Statut</th><th>Date</th><th></th></tr></thead><tbody>
 @forelse($interventions as $item)<tr><td><strong>{{ optional($item->organization)->name ?: 'Organisation indisponible' }}</strong><small>{{ optional($item->organization)->geographic_access_type==='multi_country'?'Multipays':'Unipays' }}</small></td><td><strong>{{ $item->intervention_action==='restored'?'Configuration restaurée':($item->previous_configuration_version?'Configuration modifiée':'Configuration créée') }}</strong><small>v1.{{ max(0,$item->configuration_version-1) }}</small></td><td><span class="sd-tag {{ $item->configuration_category }}">{{ $categoryLabels[$item->configuration_category]??'Configuration' }}</span></td><td>{{ optional($item->appliedBy)->name ?: 'Système' }}</td><td><span class="sd-state {{ $item->synchronization_status }}">{{ ['pending'=>'En attente','synced'=>'Synchronisée','error'=>'Échec'][$item->synchronization_status]??'Appliquée' }}</span></td><td>{{ optional($item->effective_at)->format('d/m/Y H:i') }}</td><td><a href="{{ route('configuration.platform-standards.history.show',$item) }}"><span class="material-symbols-outlined">visibility</span></a></td></tr>
 @empty<tr><td colspan="7"><x-app-empty-state icon="history" title="Aucune activité récente" description="Les interventions de configuration apparaîtront ici." /></td></tr>@endforelse
 </tbody></table></div></section>
 <aside class="sd-card sd-chart"><h2>Répartition des organisations</h2><div class="sd-donut" style="--active:{{ $sagoStats['organizations_total'] ? ($sagoStats['active']/$sagoStats['organizations_total'])*100 : 0 }}%"><strong>{{ $sagoStats['organizations_total'] }}</strong><small>Total</small></div><ul><li><i></i><span>Actives</span><b>{{ $sagoStats['active'] }}</b></li><li><i></i><span>Inactives</span><b>{{ $sagoStats['inactive'] }}</b></li><li><i></i><span>Unipays</span><b>{{ $sagoStats['single'] }}</b></li><li><i></i><span>Multipays</span><b>{{ $sagoStats['multi'] }}</b></li></ul></aside></div>
</main>
@endsection
@push('styles')<style>
.sd-page{display:grid;gap:18px;color:#17233d}.sd-head h1{font-size:22px;margin:0 0 5px}.sd-head p{margin:0;color:#66738b}.sd-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.sd-kpis a{min-width:0;display:grid;grid-template-columns:42px 1fr;gap:3px 10px;padding:16px;background:#fff;border:1px solid #e8edf3;border-radius:14px;color:#17233d}.sd-kpis i{grid-row:1/4;width:42px;height:42px;display:grid;place-items:center;border-radius:12px}.sd-kpis strong{font-size:24px}.sd-kpis span{font-size:11px;font-weight:700}.sd-kpis small{grid-column:1/-1;margin-top:10px;font-size:10px}.sd-kpis .blue{background:#eaf2ff;color:#2563eb}.sd-kpis .green{background:#e9f8ed;color:#22a447}.sd-kpis .purple{background:#f0e9ff;color:#7c3aed}.sd-kpis .orange{background:#fff3e8;color:#f57c00}.sd-kpis .navy{background:#eef2f7;color:#17233d}.sd-grid{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:16px}.sd-card{background:#fff;border:1px solid #e8edf3;border-radius:14px;overflow:hidden}.sd-card>header{display:flex;justify-content:space-between;padding:15px;border-bottom:1px solid #e8edf3}.sd-card h2{font-size:14px;margin:0}.sd-card header a{font-size:11px;color:#2563eb}.sd-table{overflow:auto}.sd-table table{width:100%;min-width:780px;border-collapse:collapse}.sd-table th,.sd-table td{padding:11px;border-bottom:1px solid #e8edf3;text-align:left;font-size:10px}.sd-table td strong,.sd-table td small{display:block}.sd-table td small{color:#778299}.sd-tag,.sd-state{padding:5px 7px;border-radius:6px;font-size:9px;font-weight:700}.sd-tag.security,.sd-tag.access{background:#f0e9ff;color:#7c3aed}.sd-tag.synchronization{background:#eaf2ff;color:#2563eb}.sd-tag.general,.sd-state.synced{background:#e9f8ed;color:#16843a}.sd-tag.platform,.sd-state.pending{background:#fff3e8;color:#c55d00}.sd-state.error{background:#fff0ef;color:#c52d29}.sd-chart{padding:17px}.sd-donut{position:relative;width:145px;height:145px;margin:24px auto;display:grid;place-content:center;text-align:center;border-radius:50%;background:conic-gradient(#22a447 0 var(--active),#f57c00 var(--active) 100%)}.sd-donut:before{content:'';position:absolute;inset:27px;background:#fff;border-radius:50%}.sd-donut>*{position:relative}.sd-chart ul{list-style:none;padding:0}.sd-chart li{display:flex;gap:8px;padding:6px;font-size:11px}.sd-chart li i{width:8px;height:8px;background:#22a447;border-radius:3px}.sd-chart li:nth-child(2) i{background:#f57c00}.sd-chart li:nth-child(3) i{background:#2563eb}.sd-chart li:nth-child(4) i{background:#7c3aed}.sd-chart li span{flex:1}
@media(max-width:1250px){.sd-kpis{grid-template-columns:repeat(3,1fr)}.sd-grid{grid-template-columns:1fr}}@media(max-width:700px){.sd-kpis{grid-template-columns:repeat(2,1fr)}.sd-kpis a:last-child{grid-column:1/-1}.sd-table{overflow:auto}}
</style>@endpush
