<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Structures · {{ $organization->name }} · PharmaCare</title>
<style>
:root{--o:#f47a20;--od:#c9580d;--ink:#33251e;--muted:#735f54;--line:#eadbd1;--soft:#fff7f0;--danger:#b42318;--green:#18733d}*{box-sizing:border-box}
body{margin:0;background:var(--soft);color:var(--ink);font-family:Inter,system-ui,sans-serif}header{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:14px 5%;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:5}
.brand{display:flex;align-items:center;gap:12px;text-decoration:none;color:var(--ink);font-weight:850}.brand img{width:46px;height:46px;object-fit:contain}nav{display:flex;gap:17px;flex-wrap:wrap}nav a{color:var(--od);font-weight:750;text-decoration:none}
main{max-width:1320px;margin:28px auto;padding:0 20px}.muted{color:var(--muted)}.toolbar,.head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}
.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;margin-bottom:22px;box-shadow:0 12px 34px #7a35000e}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}
label{display:block;font-size:14px;font-weight:750;margin:8px 0 5px}input,select,textarea{width:100%;padding:11px;border:1px solid #d8c6bb;border-radius:10px;background:#fff;font:inherit}textarea{min-height:76px}.check{display:flex;align-items:center;gap:7px}.check input{width:auto}
button,.button{border:0;border-radius:10px;padding:10px 14px;background:var(--o);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#fff1e8;color:var(--od)}.danger{background:var(--danger)}.success{background:var(--green)}
.message{padding:13px;border-radius:10px;background:#e9f8ee;color:var(--green)}.error{background:#fff0ee;color:var(--danger)}details.facility{background:#fff;border:1px solid var(--line);border-radius:18px;margin-bottom:18px;overflow:hidden}details.facility>summary{cursor:pointer;list-style:none;padding:20px;display:flex;justify-content:space-between;gap:15px;align-items:center}details.facility>summary::-webkit-details-marker{display:none}.content{padding:0 20px 20px}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef7f1;color:var(--green);font-size:12px;font-weight:800}.tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:20px}.subcard{border:1px solid var(--line);border-radius:14px;padding:15px}.item{padding:12px 0;border-top:1px solid #eee}.item:first-child{border-top:0}.compact{display:grid;grid-template-columns:1fr 1fr;gap:8px}.archives{border-left:4px solid #8b766a}.module-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.module{border:1px solid var(--line);border-radius:16px;padding:18px;display:flex;flex-direction:column;gap:10px}.module.enabled{border-color:#8bc5a0;background:#f3fbf6}.module-icon{width:43px;height:43px;display:grid;place-items:center;border-radius:12px;background:#fff0e6;color:var(--od);font-size:22px}.module h3{margin:0}.module p{margin:0;min-height:40px}.module-foot{display:flex;align-items:center;justify-content:space-between;gap:10px}.status{font-size:12px;font-weight:850;padding:5px 9px;border-radius:999px;background:#f1efed;color:var(--muted)}.enabled .status{background:#dff4e6;color:var(--green)}.switch{position:relative;width:48px;height:27px;margin:0}.switch input{opacity:0;width:0;height:0}.slider{position:absolute;inset:0;background:#baa9a0;border-radius:99px;cursor:pointer;transition:.2s}.slider:before{content:"";position:absolute;width:21px;height:21px;left:3px;top:3px;background:#fff;border-radius:50%;box-shadow:0 2px 5px #0003;transition:.2s}.switch input:checked+.slider{background:var(--green)}.switch input:checked+.slider:before{transform:translateX(21px)}
@media(max-width:980px){.grid,.tabs,.module-grid{grid-template-columns:1fr 1fr}}@media(max-width:680px){header{position:static;align-items:flex-start;flex-direction:column}.grid,.two,.tabs,.module-grid,.compact{grid-template-columns:1fr}details.facility>summary{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body>
@include('components.app-sidebar')
<header><a class="brand" href="{{ route('organizations.index') }}"><img src="{{ asset('images/pharmacare-logo.png') }}" alt="Logo PharmaCare"><span>PharmaCare · Structures</span></a>
<nav><a href="{{ route('dashboard') }}">Tableau de bord</a><a href="{{ route('organizations.index') }}">Organisations</a><a href="{{ route('organizations.missions.index',$organization) }}">Missions</a><a href="{{ route('organizations.projects.index',$organization) }}">Projets</a><a href="{{ route('organizations.catalog.index',$organization) }}">Référentiels et produits</a><a href="{{ route('users.index') }}">Utilisateurs</a></nav></header>
<main>
<div class="toolbar"><div><h1>Formations sanitaires</h1><p class="muted">{{ $organization->name }} · établissements de santé, départements, pharmacies et sites de stockage ou de dispensation.</p></div>
<div class="actions"><form method="get"><input name="search" value="{{ request('search') }}" placeholder="Rechercher une formation sanitaire"><button>Rechercher</button></form>@if(auth()->user()->hasPermission('structures.manage'))<button type="button" data-sheet-open="facility-create-sheet">＋ Nouvelle formation sanitaire</button>@endif</div></div>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message error">{{ $errors->first() }}</p>@endif

<section><h2>Formations sanitaires actives</h2>
@forelse($facilities as $facility)
<details class="facility" @if(request('facility')===$facility->id) open @endif><summary><div><strong>{{ $facility->name }}</strong><div class="muted">{{ $facility->code }} · {{ $facility->facility_type }} @if($facility->mission)· {{ $facility->mission->name }}@endif</div></div><div><span class="badge">{{ $facility->is_active ? 'Active' : 'Inactive' }}</span> <span class="secondary button">Ouvrir</span></div></summary><div class="content">
@if(auth()->user()->hasPermission('structures.manage'))
<form method="post" action="{{ route('organizations.facilities.update',[$organization,$facility]) }}">@csrf @method('PUT')
<div class="grid"><div><label>Code</label><input name="code" value="{{ $facility->code }}" required></div><div><label>Nom</label><input name="name" value="{{ $facility->name }}" required></div><div><label>Type</label><select name="facility_type">@foreach(['hospital'=>'Hôpital','health_center'=>'Centre de santé','clinic'=>'Clinique','warehouse'=>'Dépôt central','community'=>'Communautaire','other'=>'Autre'] as $value=>$label)<option value="{{ $value }}" @selected($facility->facility_type===$value)>{{ $label }}</option>@endforeach</select></div><div><label>Mission</label><select name="mission_id"><option value="">Aucune</option>@foreach($missions as $mission)<option value="{{ $mission->id }}" @selected($facility->mission_id===$mission->id)>{{ $mission->name }}</option>@endforeach</select></div><div><label>Niveau</label><input name="care_level" value="{{ $facility->care_level }}"></div><div><label>Téléphone</label><input name="phone" value="{{ $facility->phone }}"></div><div><label>E-mail</label><input name="email" type="email" value="{{ $facility->email }}"></div><div><label>Adresse</label><input name="address" value="{{ $facility->address }}"></div><div><label>Projets</label><select name="project_ids[]" multiple>@foreach($projects as $project)<option value="{{ $project->id }}" @selected($facility->projects->contains($project))>{{ $project->name }}</option>@endforeach</select></div></div><p class="actions"><label class="check"><input type="checkbox" name="is_active" value="1" @checked($facility->is_active)> Active</label><button>Enregistrer la structure</button></p></form>
<form method="post" action="{{ route('organizations.facilities.destroy',[$organization,$facility]) }}" onsubmit="return confirm('Archiver cette formation sanitaire et désactiver son utilisation ?')">@csrf @method('DELETE')<button class="danger">Archiver la structure</button></form>
@endif
<div class="tabs">
<section class="subcard"><h3>Départements</h3>
@foreach($facility->departments as $department)<div class="item"><form method="post" action="{{ route('organizations.facilities.departments.update',[$organization,$facility,$department]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $department->code }}" required><input name="name" value="{{ $department->name }}" required><select name="department_type">@foreach(['clinical'=>'Clinique','pharmacy'=>'Pharmacie','laboratory'=>'Laboratoire','logistics'=>'Logistique','administration'=>'Administration','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($department->department_type===$v)>{{ $l }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($department->is_active)> Actif</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.departments.destroy',[$organization,$facility,$department]) }}" onsubmit="return confirm('Archiver ce département ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.departments.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="department_type"><option value="clinical">Clinique</option><option value="pharmacy">Pharmacie</option><option value="laboratory">Laboratoire</option><option value="logistics">Logistique</option><option value="administration">Administration</option><option value="other">Autre</option></select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedDepartments as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.departments.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer ce département ?')">@csrf <span>{{ $item->name }} (archivé)</span> <button class="success">Restaurer</button></form>@endforeach</section>

<section class="subcard"><h3>Pharmacies</h3>
@foreach($facility->pharmacies as $pharmacy)<div class="item"><form method="post" action="{{ route('organizations.facilities.pharmacies.update',[$organization,$facility,$pharmacy]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $pharmacy->code }}" required><input name="name" value="{{ $pharmacy->name }}" required><select name="pharmacy_type">@foreach(['central'=>'Centrale','hospital'=>'Hospitalière','dispensary'=>'Dispensaire','community'=>'Communautaire','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($pharmacy->pharmacy_type===$v)>{{ $l }}</option>@endforeach</select><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}" @selected($pharmacy->department_id===$department->id)>{{ $department->name }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($pharmacy->is_active)> Active</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.pharmacies.destroy',[$organization,$facility,$pharmacy]) }}" onsubmit="return confirm('Archiver cette pharmacie ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.pharmacies.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="pharmacy_type"><option value="central">Centrale</option><option value="hospital">Hospitalière</option><option value="dispensary">Dispensaire</option><option value="community">Communautaire</option><option value="other">Autre</option></select><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedPharmacies as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.pharmacies.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer cette pharmacie ?')">@csrf <span>{{ $item->name }} (archivée)</span> <button class="success">Restaurer</button></form>@endforeach</section>

<section class="subcard"><h3>Sites</h3>
@foreach($facility->sites as $site)<div class="item"><form method="post" action="{{ route('organizations.facilities.sites.update',[$organization,$facility,$site]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $site->code }}" required><input name="name" value="{{ $site->name }}" required><select name="site_type">@foreach(['stock'=>'Stockage','dispensing'=>'Dispensation','stock_and_dispensing'=>'Stock et dispensation','quarantine'=>'Quarantaine','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($site->site_type===$v)>{{ $l }}</option>@endforeach</select><input name="location" value="{{ $site->location }}" placeholder="Emplacement"><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}" @selected($site->department_id===$department->id)>{{ $department->name }}</option>@endforeach</select><select name="pharmacy_id"><option value="">Sans pharmacie</option>@foreach($facility->pharmacies as $pharmacy)<option value="{{ $pharmacy->id }}" @selected($site->pharmacy_id===$pharmacy->id)>{{ $pharmacy->name }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($site->is_active)> Actif</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.sites.destroy',[$organization,$facility,$site]) }}" onsubmit="return confirm('Archiver ce site ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.sites.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="site_type"><option value="stock">Stockage</option><option value="dispensing">Dispensation</option><option value="stock_and_dispensing">Stock et dispensation</option><option value="quarantine">Quarantaine</option><option value="other">Autre</option></select><input name="location" placeholder="Emplacement"><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select name="pharmacy_id"><option value="">Sans pharmacie</option>@foreach($facility->pharmacies as $pharmacy)<option value="{{ $pharmacy->id }}">{{ $pharmacy->name }}</option>@endforeach</select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedSites as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.sites.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer ce site ?')">@csrf <span>{{ $item->name }} (archivé)</span> <button class="success">Restaurer</button></form>@endforeach</section>
</div></div></details>
@empty<div class="card"><p>Aucune formation sanitaire enregistrée.</p></div>@endforelse
{{ $facilities->links() }}</section>

@if($archivedFacilities->isNotEmpty())<section class="card archives"><h2>Formations sanitaires archivées</h2>@foreach($archivedFacilities as $item)<div class="item head"><div><strong>{{ $item->name }}</strong><div class="muted">{{ $item->code }} · archivée le {{ $item->deleted_at?->format('d/m/Y H:i') }}</div></div><form method="post" action="{{ route('organizations.facilities.restore',[$organization,$item->id]) }}" onsubmit="return confirm('Restaurer cette formation sanitaire ?')">@csrf<button class="success">Restaurer</button></form></div>@endforeach</section>@endif

@if(auth()->user()->hasPermission('modules.manage'))
<section class="card"><h2>Activation des modules</h2><p class="muted">Activez les fonctions disponibles pour l’organisation, un projet ou une formation sanitaire.</p>
<div class="module-grid">@foreach($moduleCodes as $code=>$module)@php($current=$activations->get("organization:{$organization->id}:{$code}"))<form class="module {{ ($current?->is_enabled ?? true) ? 'enabled' : '' }}" method="post" action="{{ route('organizations.module-activations.update',$organization) }}">@csrf @method('PUT')<div class="module-icon" aria-hidden="true">{{ $module['icon'] }}</div><div><h3>{{ $module['name'] }}</h3><p class="muted">{{ $module['description'] }}</p></div><label>Périmètre d’activation</label><select name="target"><option value="organization:{{ $organization->id }}">Organisation · {{ $organization->name }}</option>@foreach($projects as $project)<option value="project:{{ $project->id }}">Projet · {{ $project->name }}</option>@endforeach @foreach($facilities as $facility)<option value="facility:{{ $facility->id }}">Formation sanitaire · {{ $facility->name }}</option>@endforeach</select><input type="hidden" name="module_code" value="{{ $code }}"><input type="hidden" name="is_enabled" value="0"><div class="module-foot"><span class="status">{{ ($current?->is_enabled ?? true) ? 'Activé' : 'Désactivé' }}</span><label class="switch" aria-label="Activer ou désactiver {{ $module['name'] }}"><input type="checkbox" name="is_enabled" value="1" @checked($current?->is_enabled ?? true) onchange="this.form.submit()"><span class="slider"></span></label></div></form>@endforeach</div></section>
@endif
@if(auth()->user()->hasPermission('structures.manage'))
<x-form-sheet id="facility-create-sheet" title="Nouvelle formation sanitaire" description="Ajoutez un établissement de santé et ses informations opérationnelles.">
@if($errors->any())<div class="form-sheet-error">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('organizations.facilities.store',$organization) }}">@csrf
<div class="grid"><div><label>Nom de la formation sanitaire *</label><input name="name" value="{{ old('name') }}" required></div><div><label>Code unique *</label><input name="code" value="{{ old('code') }}" required></div><div><label>Type d’établissement *</label><select name="facility_type" required>@foreach(['hospital'=>'Hôpital','health_center'=>'Centre de santé','clinic'=>'Clinique','warehouse'=>'Dépôt pharmaceutique central','community'=>'Formation sanitaire communautaire','other'=>'Autre'] as $value=>$label)<option value="{{ $value }}" @selected(old('facility_type')===$value)>{{ $label }}</option>@endforeach</select></div><div><label>Mission / pays</label><select name="mission_id"><option value="">Aucune mission</option>@foreach($missions as $mission)<option value="{{ $mission->id }}" @selected(old('mission_id')===$mission->id)>{{ $mission->name }} · {{ $mission->country->name }}</option>@endforeach</select></div><div><label>Niveau de soins</label><input name="care_level" value="{{ old('care_level') }}"></div><div><label>Téléphone</label><input name="phone" type="tel" value="{{ old('phone') }}"></div><div><label>Adresse e-mail</label><input name="email" type="email" value="{{ old('email') }}"></div><div><label>Adresse</label><input name="address" value="{{ old('address') }}"></div><div><label>Projets associés</label><select name="project_ids[]" multiple>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(in_array($project->id,old('project_ids',[])))>{{ $project->name }}</option>@endforeach</select></div><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',true))> Formation sanitaire active</label></div>
<div class="form-sheet-actions"><button class="secondary" type="button" data-sheet-close="facility-create-sheet">Annuler</button><button type="submit">Enregistrer</button></div></form>
</x-form-sheet>
@endif
</main></body></html>
