<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Structures · {{ $organization->name }} · PharmaCare</title>
<style>
:root{--o:#f47a20;--od:#c9580d;--ink:#33251e;--muted:#735f54;--line:#eadbd1;--soft:#fff7f0;--danger:#b42318;--green:#18733d}*{box-sizing:border-box}
body{margin:0;background:var(--soft);color:var(--ink);font-family:Inter,system-ui,sans-serif}header{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:14px 5%;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:5}
.brand{display:flex;align-items:center;gap:12px;text-decoration:none;color:var(--ink);font-weight:850}.brand img{width:46px;height:46px;object-fit:contain}nav{display:flex;gap:17px;flex-wrap:wrap}nav a{color:var(--od);font-weight:750;text-decoration:none}
main{max-width:1320px;margin:28px auto;padding:0 20px}.muted{color:var(--muted)}.toolbar,.head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}
.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;margin-bottom:22px;box-shadow:0 12px 34px #7a35000e}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}
label{display:block;font-size:14px;font-weight:750;margin:8px 0 5px}input,select,textarea{width:100%;padding:11px;border:1px solid #d8c6bb;border-radius:10px;background:#fff;font:inherit}textarea{min-height:76px}.check{display:flex;align-items:center;gap:7px}.check input{width:auto}
button,.button{border:0;border-radius:10px;padding:10px 14px;background:var(--o);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#fff1e8;color:var(--od)}.danger{background:var(--danger)}.success{background:var(--green)}
.message{padding:13px;border-radius:10px;background:#e9f8ee;color:var(--green)}.error{background:#fff0ee;color:var(--danger)}details.facility{background:#fff;border:1px solid var(--line);border-radius:18px;margin-bottom:18px;overflow:hidden}details.facility>summary{cursor:pointer;list-style:none;padding:20px;display:flex;justify-content:space-between;gap:15px;align-items:center}details.facility>summary::-webkit-details-marker{display:none}.content{padding:0 20px 20px}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef7f1;color:var(--green);font-size:12px;font-weight:800}.tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:20px}.subcard{border:1px solid var(--line);border-radius:14px;padding:15px}.item{padding:12px 0;border-top:1px solid #eee}.item:first-child{border-top:0}.compact{display:grid;grid-template-columns:1fr 1fr;gap:8px}.archives{border-left:4px solid #8b766a}.module-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.module{border:1px solid var(--line);border-radius:12px;padding:12px}
@media(max-width:980px){.grid,.tabs,.module-grid{grid-template-columns:1fr 1fr}}@media(max-width:680px){header{position:static;align-items:flex-start;flex-direction:column}.grid,.two,.tabs,.module-grid,.compact{grid-template-columns:1fr}details.facility>summary{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body>
<header><a class="brand" href="{{ route('organizations.index') }}"><img src="{{ asset('images/pharmacare-logo.png') }}" alt="Logo PharmaCare"><span>PharmaCare · Structures</span></a>
<nav><a href="{{ route('organizations.index') }}">Organisations</a><a href="{{ route('organizations.missions.index',$organization) }}">Missions</a><a href="{{ route('organizations.projects.index',$organization) }}">Projets</a><a href="{{ route('organizations.catalog.index',$organization) }}">Référentiels et produits</a><a href="{{ route('dashboard') }}">Utilisateurs</a></nav></header>
<main>
<div class="toolbar"><div><h1>{{ $organization->name }}</h1><p class="muted">Formations sanitaires, départements, pharmacies et sites de stockage ou dispensation.</p></div>
<form method="get"><input name="search" value="{{ request('search') }}" placeholder="Rechercher une structure"><button>Rechercher</button></form></div>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message error">{{ $errors->first() }}</p>@endif

@if(auth()->user()->hasPermission('structures.manage'))
<section class="card"><div class="head"><div><h2>Nouvelle formation sanitaire</h2><p class="muted">Créez la structure puis ouvrez-la pour configurer ses unités opérationnelles.</p></div></div>
<form method="post" action="{{ route('organizations.facilities.store',$organization) }}">@csrf
<div class="grid"><div><label>Code</label><input name="code" value="{{ old('code') }}" required></div><div><label>Nom</label><input name="name" value="{{ old('name') }}" required></div><div><label>Type</label><select name="facility_type" required><option value="hospital">Hôpital</option><option value="health_center">Centre de santé</option><option value="clinic">Clinique</option><option value="warehouse">Dépôt central</option><option value="community">Structure communautaire</option><option value="other">Autre</option></select></div>
<div><label>Mission</label><select name="mission_id"><option value="">Aucune mission</option>@foreach($missions as $mission)<option value="{{ $mission->id }}">{{ $mission->name }} · {{ $mission->country->name }}</option>@endforeach</select></div><div><label>Niveau de soins</label><input name="care_level"></div><div><label>Téléphone</label><input name="phone"></div><div><label>E-mail</label><input name="email" type="email"></div><div><label>Adresse</label><input name="address"></div><div><label>Projets associés</label><select name="project_ids[]" multiple>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div></div>
<p><label class="check"><input type="checkbox" name="is_active" value="1" checked> Structure active</label></p><button>Créer la formation sanitaire</button></form></section>
@endif

<section><h2>Structures actives</h2>
@forelse($facilities as $facility)
<details class="facility" @if(request('facility')===$facility->id) open @endif><summary><div><strong>{{ $facility->name }}</strong><div class="muted">{{ $facility->code }} · {{ $facility->facility_type }} @if($facility->mission)· {{ $facility->mission->name }}@endif</div></div><div><span class="badge">{{ $facility->is_active ? 'Active' : 'Inactive' }}</span> <span class="secondary button">Ouvrir</span></div></summary><div class="content">
@if(auth()->user()->hasPermission('structures.manage'))
<form method="post" action="{{ route('organizations.facilities.update',[$organization,$facility]) }}">@csrf @method('PUT')
<div class="grid"><div><label>Code</label><input name="code" value="{{ $facility->code }}" required></div><div><label>Nom</label><input name="name" value="{{ $facility->name }}" required></div><div><label>Type</label><select name="facility_type">@foreach(['hospital'=>'Hôpital','health_center'=>'Centre de santé','clinic'=>'Clinique','warehouse'=>'Dépôt central','community'=>'Communautaire','other'=>'Autre'] as $value=>$label)<option value="{{ $value }}" @selected($facility->facility_type===$value)>{{ $label }}</option>@endforeach</select></div><div><label>Mission</label><select name="mission_id"><option value="">Aucune</option>@foreach($missions as $mission)<option value="{{ $mission->id }}" @selected($facility->mission_id===$mission->id)>{{ $mission->name }}</option>@endforeach</select></div><div><label>Niveau</label><input name="care_level" value="{{ $facility->care_level }}"></div><div><label>Téléphone</label><input name="phone" value="{{ $facility->phone }}"></div><div><label>E-mail</label><input name="email" type="email" value="{{ $facility->email }}"></div><div><label>Adresse</label><input name="address" value="{{ $facility->address }}"></div><div><label>Projets</label><select name="project_ids[]" multiple>@foreach($projects as $project)<option value="{{ $project->id }}" @selected($facility->projects->contains($project))>{{ $project->name }}</option>@endforeach</select></div></div><p class="actions"><label class="check"><input type="checkbox" name="is_active" value="1" @checked($facility->is_active)> Active</label><button>Enregistrer la structure</button></p></form>
<form method="post" action="{{ route('organizations.facilities.destroy',[$organization,$facility]) }}" onsubmit="return confirm('Archiver cette formation sanitaire et désactiver son utilisation ?')">@csrf @method('DELETE')<button class="danger">Archiver la structure</button></form>
@endif
<div class="tabs">
<section class="subcard"><h3>Départements</h3>
@foreach($facility->departments as $department)<div class="item"><form method="post" action="{{ route('organizations.facilities.departments.update',[$organization,$facility,$department]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $department->code }}" required><input name="name" value="{{ $department->name }}" required><select name="department_type">@foreach(['clinical'=>'Clinique','pharmacy'=>'Pharmacie','laboratory'=>'Laboratoire','logistics'=>'Logistique','administration'=>'Administration','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($department->department_type===$v)>{{ $l }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($department->is_active)> Actif</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.departments.destroy',[$organization,$facility,$department]) }}" onsubmit="return confirm('Archiver ce département ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.departments.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="department_type"><option value="clinical">Clinique</option><option value="pharmacy">Pharmacie</option><option value="laboratory">Laboratoire</option><option value="logistics">Logistique</option><option value="administration">Administration</option><option value="other">Autre</option></select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedDepartments as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.departments.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer ce département ?')">@csrf <span>{{ $item->name }} (archivé)</span> <button class="success">Restaurer</button></form>@endforeach</section>

<section class="subcard"><h3>Pharmacies</h3>
@foreach($facility->pharmacies as $pharmacy)<div class="item"><form method="post" action="{{ route('organizations.facilities.pharmacies.update',[$organization,$facility,$pharmacy]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $pharmacy->code }}" required><input name="name" value="{{ $pharmacy->name }}" required><select name="pharmacy_type">@foreach(['central'=>'Centrale','hospital'=>'Hospitalière','dispensary'=>'Dispensaire','community'=>'Communautaire','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($pharmacy->pharmacy_type===$v)>{{ $l }}</option>@endforeach</select><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}" @selected($pharmacy->department_id===$department->id)>{{ $department->name }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($pharmacy->is_active)> Active</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.pharmacies.destroy',[$organization,$facility,$pharmacy]) }}" onsubmit="return confirm('Archiver cette pharmacie ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.pharmacies.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="pharmacy_type"><option value="central">Centrale</option><option value="hospital">Hospitalière</option><option value="dispensary">Dispensaire</option><option value="community">Communautaire</option><option value="other">Autre</option></select><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedPharmacies as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.pharmacies.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer cette pharmacie ?')">@csrf <span>{{ $item->name }} (archivée)</span> <button class="success">Restaurer</button></form>@endforeach</section>

<section class="subcard"><h3>Sites</h3>
@foreach($facility->sites as $site)<div class="item"><form method="post" action="{{ route('organizations.facilities.sites.update',[$organization,$facility,$site]) }}">@csrf @method('PUT')<div class="compact"><input name="code" value="{{ $site->code }}" required><input name="name" value="{{ $site->name }}" required><select name="site_type">@foreach(['stock'=>'Stockage','dispensing'=>'Dispensation','stock_and_dispensing'=>'Stock et dispensation','quarantine'=>'Quarantaine','other'=>'Autre'] as $v=>$l)<option value="{{ $v }}" @selected($site->site_type===$v)>{{ $l }}</option>@endforeach</select><input name="location" value="{{ $site->location }}" placeholder="Emplacement"><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}" @selected($site->department_id===$department->id)>{{ $department->name }}</option>@endforeach</select><select name="pharmacy_id"><option value="">Sans pharmacie</option>@foreach($facility->pharmacies as $pharmacy)<option value="{{ $pharmacy->id }}" @selected($site->pharmacy_id===$pharmacy->id)>{{ $pharmacy->name }}</option>@endforeach</select><label class="check"><input type="checkbox" name="is_active" value="1" @checked($site->is_active)> Actif</label></div><button>Modifier</button></form><form method="post" action="{{ route('organizations.facilities.sites.destroy',[$organization,$facility,$site]) }}" onsubmit="return confirm('Archiver ce site ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></div>@endforeach
@if(auth()->user()->hasPermission('structures.manage'))<form class="item" method="post" action="{{ route('organizations.facilities.sites.store',[$organization,$facility]) }}">@csrf<div class="compact"><input name="code" placeholder="Code" required><input name="name" placeholder="Nom" required><select name="site_type"><option value="stock">Stockage</option><option value="dispensing">Dispensation</option><option value="stock_and_dispensing">Stock et dispensation</option><option value="quarantine">Quarantaine</option><option value="other">Autre</option></select><input name="location" placeholder="Emplacement"><select name="department_id"><option value="">Sans département</option>@foreach($facility->departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select name="pharmacy_id"><option value="">Sans pharmacie</option>@foreach($facility->pharmacies as $pharmacy)<option value="{{ $pharmacy->id }}">{{ $pharmacy->name }}</option>@endforeach</select><input type="hidden" name="is_active" value="1"></div><button>Ajouter</button></form>@endif
@foreach($facility->archivedSites as $item)<form class="item archives" method="post" action="{{ route('organizations.facilities.sites.restore',[$organization,$facility,$item->id]) }}" onsubmit="return confirm('Restaurer ce site ?')">@csrf <span>{{ $item->name }} (archivé)</span> <button class="success">Restaurer</button></form>@endforeach</section>
</div></div></details>
@empty<div class="card"><p>Aucune formation sanitaire enregistrée.</p></div>@endforelse
{{ $facilities->links() }}</section>

@if($archivedFacilities->isNotEmpty())<section class="card archives"><h2>Formations sanitaires archivées</h2>@foreach($archivedFacilities as $item)<div class="item head"><div><strong>{{ $item->name }}</strong><div class="muted">{{ $item->code }} · archivée le {{ $item->deleted_at?->format('d/m/Y H:i') }}</div></div><form method="post" action="{{ route('organizations.facilities.restore',[$organization,$item->id]) }}" onsubmit="return confirm('Restaurer cette formation sanitaire ?')">@csrf<button class="success">Restaurer</button></form></div>@endforeach</section>@endif

@if(auth()->user()->hasPermission('modules.manage'))
<section class="card"><h2>Activation des modules</h2><p class="muted">Définissez précisément les fonctions disponibles au niveau de l’organisation, d’un projet ou d’une formation sanitaire.</p>
<div class="module-grid">@foreach($moduleCodes as $code=>$label)<form class="module" method="post" action="{{ route('organizations.module-activations.update',$organization) }}">@csrf @method('PUT')<strong>{{ $label }}</strong><label>Périmètre</label><select name="target"><option value="organization:{{ $organization->id }}">Organisation</option>@foreach($projects as $project)<option value="project:{{ $project->id }}">Projet · {{ $project->name }}</option>@endforeach @foreach($facilities as $facility)<option value="facility:{{ $facility->id }}">Structure · {{ $facility->name }}</option>@endforeach</select><input type="hidden" name="module_code" value="{{ $code }}"><label>État</label><select name="is_enabled"><option value="1">Activé</option><option value="0">Désactivé</option></select><button>Appliquer</button></form>@endforeach</div></section>
@endif
</main></body></html>
