<?php
namespace App\Http\Controllers\Web;
use App\Http\Controllers\Controller; use App\Models\Project; use App\Models\StandardList; use App\Services\GovernanceService; use App\Services\StandardListGenerationService; use App\Services\UserScopeService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\View\View;
class ProjectStandardListController extends Controller {
 public function __construct(private UserScopeService $scopes,private StandardListGenerationService $generator,private GovernanceService $governance){}
 public function show(Request $r,Project $project):View{$this->access($r,$project);return $this->page($r,$project);}
 public function generate(Request $r,Project $project):View{$this->manage($r,$project);$context=$this->context($r);return $this->page($r,$project,$context,$this->generator->generate($project,$context));}
 public function save(Request $r,Project $project):RedirectResponse{$this->manage($r,$project);$context=$this->context($r);$d=$r->validate(['code'=>['required','alpha_dash','max:60'],'name'=>['required','string','max:190'],'product_ids'=>['required','array','min:1'],'product_ids.*'=>['uuid','distinct']]);abort_unless($project->organization->products()->whereIn('id',$d['product_ids'])->count()===count($d['product_ids']),422);DB::transaction(function()use($project,$d,$context){$list=StandardList::firstOrCreate(['organization_id'=>$project->organization_id,'scope_type'=>'project','scope_id'=>$project->id],['code'=>$d['code'],'name'=>$d['name'],'is_active'=>true]);$list->update(['code'=>$d['code'],'name'=>$d['name'],'is_active'=>true]);$v=$list->versions()->create([...$context,'version_number'=>((int)$list->versions()->max('version_number'))+1,'status'=>'draft']);$v->products()->sync($d['product_ids']);});return redirect()->route('projects.standard-list.show',$project)->with('status','Brouillon enregistré.');}
 public function publish(Request $r,Project $project,StandardList $list):RedirectResponse{$this->manage($r,$project);abort_unless($list->scope_id===$project->id,404);$v=$list->versions()->where('status','draft')->latest('version_number')->firstOrFail();abort_unless($v->products()->exists(),422);DB::transaction(function()use($list,$v,$r){$list->versions()->where('status','published')->update(['status'=>'superseded']);$v->update(['status'=>'published','published_by'=>$r->user()->id,'published_at'=>now()]);});return back()->with('status','Liste standard validée et activée.');}
 private function page(Request $r,Project $p,?array $context=null,$recommended=null):View{$list=StandardList::where('scope_type','project')->where('scope_id',$p->id)->with(['versions'=>fn($q)=>$q->with('products')->latest('version_number')])->first();return view('projects.standard-list',['project'=>$p->load('organization','mission.country'),'list'=>$list,'options'=>$this->generator->options($p->organization),'context'=>$context??$this->generator->withProjectDefaults($p,[]),'needsRegeneration'=>$this->generator->needsRegeneration($p,$list?->versions->firstWhere('status','published')),'recommended'=>$recommended??collect(),'canManage'=>$this->governance->roleCode($r->user())===GovernanceService::COORDINATION_ADMIN&&$r->user()->hasPermission('standard_lists.manage')]);}
 private function context(Request $r):array{$p=$r->route('project');$c=$this->generator->withProjectDefaults($p,$r->validate(['care_level_id'=>['nullable','uuid'],'facility_category_id'=>['required','uuid'],'target_population_ids'=>['nullable','array'],'target_population_ids.*'=>['uuid'],'pathology_ids'=>['nullable','array'],'pathology_ids.*'=>['uuid'],'laboratory_exam_ids'=>['nullable','array'],'laboratory_exam_ids.*'=>['uuid']]));if(empty($c['care_level_id'])||empty($c['target_population_ids']))throw \Illuminate\Validation\ValidationException::withMessages(['care_level_id'=>'Configurez la configuration médicale du projet ou sélectionnez un niveau de soins et une population cible.']);return $c;}
 private function access(Request $r,Project $p):void{abort_unless($this->scopes->projects($r->user())->whereKey($p->id)->exists(),404);} private function manage(Request $r,Project $p):void{$this->access($r,$p);abort_unless($this->governance->roleCode($r->user())===GovernanceService::COORDINATION_ADMIN&&$r->user()->hasPermission('standard_lists.manage'),403);}
}
