<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Missions · PharmaCare</title>
<style>:root{--o:#f47a20;--s:#fff7f0;--d:#382319}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:var(--s);color:var(--d)}header{background:var(--o);padding:18px 5%;color:white;display:flex;gap:20px}header a{color:white}main{max-width:1200px;margin:auto;padding:28px 5%}.card{background:white;padding:22px;border-radius:16px;margin-bottom:22px;box-shadow:0 10px 30px #7a350015}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}input,select{width:100%;padding:11px;border:1px solid #dbcabd;border-radius:9px}button{background:var(--o);color:white;border:0;padding:11px 15px;border-radius:9px;font-weight:700}.danger{background:#b42318}.message{background:#eaf8ef;color:#176b3a;padding:13px;border-radius:9px}.item{border-top:1px solid #f1e1d5;padding:18px 0}.head{display:flex;justify-content:space-between;align-items:center;gap:12px}.muted{color:#78665a}@media(max-width:800px){.grid{grid-template-columns:1fr}.head{display:block}}</style></head>
<body>@include('components.app-sidebar')<header><a href="{{ route('organizations.index') }}"><img src="{{ asset('images/pharmacare-logo.png') }}" alt="Logo PharmaCare" style="width:42px;height:42px;object-fit:contain;background:#fff;border-radius:9px;vertical-align:middle"> <strong>PharmaCare · Missions</strong></a><a href="{{ route('organizations.index') }}">← Organisations</a><a href="{{ route('organizations.projects.index',$organization) }}">Projets</a><a href="{{ route('dashboard') }}">Tableau de bord</a></header><main>
<h1>{{ $organization->name }}</h1><p class="muted">Pays et missions d’intervention de l’organisation.</p>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message">{{ $errors->first() }}</p>@endif
<div class="grid"><section class="card"><h2>Ajouter un pays</h2><form method="post" action="{{ route('countries.store') }}">@csrf<input name="iso2" maxlength="2" placeholder="Code ISO (CM)" required><p><input name="name" placeholder="Nom du pays" required></p><button>Ajouter le pays</button></form></section>
<section class="card" style="grid-column:span 2"><h2>Nouvelle mission</h2><form method="post" action="{{ route('organizations.missions.store',$organization) }}">@csrf<div class="grid"><input name="code" placeholder="Code mission" required><input name="name" placeholder="Nom de la mission" required><select name="country_id" required><option value="">Sélectionner un pays</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }} ({{ $country->iso2 }})</option>@endforeach</select><input type="date" name="starts_on" title="Date de début"><input type="date" name="ends_on" title="Date de fin"><label><input style="width:auto" type="checkbox" name="is_active" value="1" checked> Mission active</label></div><p><button>Créer la mission</button></p></form></section></div>
<section class="card"><h2>Missions existantes</h2>@forelse($missions as $mission)<article class="item"><form method="post" action="{{ route('organizations.missions.update',[$organization,$mission]) }}">@csrf @method('PUT')<div class="head"><div><strong>{{ $mission->name }}</strong><div class="muted">{{ $mission->code }} · {{ $mission->country->name }}</div></div><div><label><input style="width:auto" type="checkbox" name="is_active" value="1" @checked($mission->is_active)> Active</label> <button>Enregistrer</button></div></div><div class="grid" style="margin-top:12px"><input name="code" value="{{ $mission->code }}" required><input name="name" value="{{ $mission->name }}" required><select name="country_id" required>@foreach($countries as $country)<option value="{{ $country->id }}" @selected($mission->country_id===$country->id)>{{ $country->name }}</option>@endforeach</select><input type="date" name="starts_on" value="{{ $mission->starts_on?->format('Y-m-d') }}"><input type="date" name="ends_on" value="{{ $mission->ends_on?->format('Y-m-d') }}"></div></form><form method="post" action="{{ route('organizations.missions.destroy',[$organization,$mission]) }}" onsubmit="return confirm('Archiver cette mission ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></article>@empty<p>Aucune mission.</p>@endforelse {{ $missions->links() }}</section>
@if($archivedMissions->isNotEmpty())<section class="card"><h2>Missions archivées</h2>@foreach($archivedMissions as $mission)<article class="item"><div class="head"><div><strong>{{ $mission->name }}</strong><div class="muted">{{ $mission->code }} · {{ $mission->country->name }}</div></div><form method="post" action="{{ route('organizations.missions.restore',[$organization,$mission->id]) }}" onsubmit="return confirm('Restaurer cette mission ?')">@csrf<button>Restaurer</button></form></div></article>@endforeach</section>@endif
</main></body></html>
