<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mon profil · PharmaCare</title>
<style>:root{--o:#f47a20;--s:#fff7f0;--d:#382319}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:var(--s);color:var(--d)}header{background:var(--o);color:white;padding:12px 6%;display:flex;align-items:center;gap:14px}header img{width:44px;height:44px;object-fit:cover;border-radius:50%;background:white}header a{color:white}main{max-width:1050px;margin:30px auto;padding:0 20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:white;padding:24px;border-radius:16px;margin-bottom:20px;box-shadow:0 10px 30px #7a350015}label{display:block;font-weight:700;margin-top:12px}input{width:100%;padding:12px;border:1px solid #dbcabd;border-radius:9px;margin-top:5px}button{background:var(--o);color:white;border:0;padding:11px 15px;border-radius:9px;font-weight:700}.message{background:#eaf8ef;padding:12px;border-radius:8px}.item{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #eee;padding:13px 0}.muted{color:#78665a;font-size:13px}@media(max-width:760px){.grid{grid-template-columns:1fr}.item{display:block}.item form{margin-top:8px}}</style></head>
<body><header><img src="{{ asset('images/pharmacare-logo.png') }}" alt=""><a href="{{ route('dashboard') }}">← Administration</a><strong>Mon profil</strong></header><main><h1>{{ $user->name }}</h1><p>{{ $user->roles->first()?->name ?? 'Utilisateur' }}</p>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message">{{ $errors->first() }}</p>@endif
<div class="grid"><section class="card"><h2>Informations personnelles</h2><form method="post" action="{{ route('profile.update') }}">@csrf @method('PUT')<label>Prénom<input name="first_name" value="{{ old('first_name',$user->first_name ?: explode(' ',$user->name)[0]) }}" required></label><label>Nom<input name="last_name" value="{{ old('last_name',$user->last_name ?: trim(str_replace(explode(' ',$user->name)[0],'',$user->name))) }}" required></label><label>Identifiant<input name="username" value="{{ old('username',$user->username) }}" required></label><label>Adresse e-mail<input name="email" type="email" value="{{ old('email',$user->email) }}" required></label><label>Téléphone<input name="phone" value="{{ old('phone',$user->phone) }}"></label><p><button>Mettre à jour mon profil</button></p></form></section>
<section class="card"><h2>Changer mon mot de passe</h2><p class="muted">12 caractères minimum avec majuscule, minuscule, chiffre et symbole.</p><form method="post" action="{{ route('profile.password') }}">@csrf @method('PUT')<label>Mot de passe actuel<input name="current_password" type="password" required></label><label>Nouveau mot de passe<input name="password" type="password" required></label><label>Confirmation<input name="password_confirmation" type="password" required></label><p><button>Changer le mot de passe</button></p></form></section></div>
<section class="card"><h2>Appareils mobiles autorisés</h2>@forelse($devices as $device)<div class="item"><div><strong>{{ $device->name }}</strong><div class="muted">{{ strtoupper($device->platform) }} · Dernière activité {{ $device->last_seen_at?->format('d/m/Y H:i') ?: 'inconnue' }} · {{ $device->revoked_at ? 'Révoqué' : 'Autorisé' }}</div></div>@if(!$device->revoked_at)<form method="post" action="{{ route('profile.devices.revoke',$device) }}" onsubmit="return confirm('Révoquer cet appareil ?')">@csrf @method('DELETE')<button>Révoquer</button></form>@endif</div>@empty<p>Aucun appareil enregistré.</p>@endforelse</section>
<section class="card"><h2>Sessions Web</h2>@forelse($sessions as $session)<div class="item"><div><strong>{{ $session->id===$currentSessionId ? 'Session actuelle' : 'Session Web' }}</strong><div class="muted">{{ $session->ip_address }} · {{ \Illuminate\Support\Str::limit($session->user_agent,90) }} · {{ \Carbon\Carbon::createFromTimestamp($session->last_activity)->format('d/m/Y H:i') }}</div></div>@if($session->id!==$currentSessionId)<form method="post" action="{{ route('profile.sessions.revoke',$session->id) }}" onsubmit="return confirm('Révoquer cette session Web ?')">@csrf @method('DELETE')<button>Révoquer</button></form>@endif</div>@empty<p>Aucune session enregistrée.</p>@endforelse</section>
</main></body></html>
