// Fichier généré depuis backend/config/pharmacare_languages.php (ne pas modifier à la main).

/// Toutes les langues ISO 639-1, français et anglais d’abord.
const languageCatalog = <String, String>{
  'fr': 'Français',
  'en': 'English (anglais)',
  'ab': 'аҧсуа бызшәа (abkhaze)',
  'aa': 'Afaraf (afar)',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'sq': 'Shqip (albanais)',
  'de': 'Deutsch (allemand)',
  'am': 'አማርኛ (amharique)',
  'ar': 'العربية (arabe)',
  'an': 'aragonés (aragonais)',
  'hy': 'Հայերեն (arménien)',
  'as': 'অসমীয়া (assamais)',
  'av': 'авар мацӀ (avar)',
  'ae': 'avesta (avestique)',
  'ay': 'aymar aru (aymara)',
  'az': 'azərbaycan dili (azéri)',
  'ba': 'башҡорт теле (bachkir)',
  'bm': 'bamanankan (bambara)',
  'eu': 'euskara (basque)',
  'bn': 'বাংলা (bengali)',
  'bi': 'Bislama (bichelamar)',
  'be': 'беларуская мова (biélorusse)',
  'my': 'ဗမာစာ (birman)',
  'bs': 'bosanski jezik (bosniaque)',
  'br': 'brezhoneg (breton)',
  'bg': 'български език (bulgare)',
  'ks': 'कश्मीरी (cachemiri)',
  'ca': 'català (catalan)',
  'ch': 'Chamoru (chamorro)',
  'ny': 'chiCheŵa (chichewa)',
  'zh': '中文 (chinois)',
  'si': 'සිංහල (cingalais)',
  'ko': '한국어 (coréen)',
  'kw': 'Kernewek (cornique)',
  'co': 'corsu (corse)',
  'ht': 'Kreyòl ayisyen (créole haïtien)',
  'cr': 'ᓀᐦᐃᔭᐍᐏᐣ (cri)',
  'hr': 'hrvatski jezik (croate)',
  'da': 'dansk (danois)',
  'dv': 'ދިވެހި (divehi)',
  'dz': 'རྫོང་ཁ (dzongkha)',
  'es': 'Español (espagnol)',
  'eo': 'Esperanto (espéranto)',
  'et': 'eesti keel (estonien)',
  'ee': 'Eʋegbe (éwé)',
  'fo': 'føroyskt (féroïen)',
  'fj': 'vosa Vakaviti (fidjien)',
  'fi': 'suomi (finnois)',
  'fy': 'Frysk (frison occidental)',
  'gd': 'Gàidhlig (gaélique écossais)',
  'gl': 'galego (galicien)',
  'cy': 'Cymraeg (gallois)',
  'lg': 'Luganda (ganda)',
  'ka': 'ქართული (géorgien)',
  'el': 'Ελληνικά (grec)',
  'kl': 'kalaallisut (groenlandais)',
  'gn': 'Avañe’ẽ (guarani)',
  'gu': 'ગુજરાતી (gujarati)',
  'ha': 'Hausa (haoussa)',
  'he': 'עברית (hébreu)',
  'hz': 'Otjiherero (héréro)',
  'hi': 'हिन्दी (hindi)',
  'ho': 'Hiri Motu',
  'hu': 'magyar (hongrois)',
  'io': 'Ido',
  'ig': 'Asụsụ Igbo (igbo)',
  'id': 'Bahasa Indonesia (indonésien)',
  'ia': 'Interlingua',
  'ie': 'Interlingue',
  'iu': 'ᐃᓄᒃᑎᑐᑦ (inuktitut)',
  'ik': 'Iñupiaq (inupiaq)',
  'ga': 'Gaeilge (irlandais)',
  'is': 'Íslenska (islandais)',
  'it': 'Italiano (italien)',
  'ja': '日本語 (japonais)',
  'jv': 'basa Jawa (javanais)',
  'kn': 'ಕನ್ನಡ (kannada)',
  'kr': 'Kanuri (kanouri)',
  'kk': 'қазақ тілі (kazakh)',
  'km': 'ខ្មែរ (khmer)',
  'kg': 'Kikongo',
  'ki': 'Gĩkũyũ (kikuyu)',
  'rw': 'Ikinyarwanda (kinyarwanda)',
  'ky': 'Кыргызча (kirghize)',
  'rn': 'Ikirundi (kirundi)',
  'kv': 'коми кыв (komi)',
  'kj': 'Kuanyama',
  'ku': 'Kurdî (kurde)',
  'lo': 'ພາສາລາວ (lao)',
  'la': 'latine (latin)',
  'lv': 'latviešu valoda (letton)',
  'li': 'Limburgs (limbourgeois)',
  'ln': 'Lingála (lingala)',
  'lt': 'lietuvių kalba (lituanien)',
  'lu': 'Kiluba (luba-katanga)',
  'lb': 'Lëtzebuergesch (luxembourgeois)',
  'mk': 'македонски јазик (macédonien)',
  'ms': 'Bahasa Melayu (malais)',
  'ml': 'മലയാളം (malayalam)',
  'mg': 'fiteny malagasy (malgache)',
  'mt': 'Malti (maltais)',
  'gv': 'Gaelg (mannois)',
  'mi': 'te reo Māori (maori)',
  'mr': 'मराठी (marathi)',
  'mh': 'Kajin M̧ajeļ (marshallais)',
  'mn': 'Монгол хэл (mongol)',
  'na': 'Dorerin Naoero (nauruan)',
  'nv': 'Diné bizaad (navajo)',
  'nd': 'isiNdebele (ndébélé du Nord)',
  'nr': 'isiNdebele (ndébélé du Sud)',
  'ng': 'Owambo (ndonga)',
  'nl': 'Nederlands (néerlandais)',
  'ne': 'नेपाली (népalais)',
  'no': 'Norsk (norvégien)',
  'nb': 'Norsk bokmål (norvégien bokmål)',
  'nn': 'Norsk nynorsk (norvégien nynorsk)',
  'oc': 'occitan',
  'or': 'ଓଡ଼ିଆ (odia)',
  'oj': 'ᐊᓂᔑᓈᐯᒧᐎᓐ (ojibwé)',
  'om': 'Afaan Oromoo (oromo)',
  'os': 'ирон æвзаг (ossète)',
  'ug': 'ئۇيغۇرچە (ouïghour)',
  'ur': 'اردو (ourdou)',
  'uz': 'Oʻzbek (ouzbek)',
  'ps': 'پښتو (pachto)',
  'pi': 'पाऴि (pali)',
  'pa': 'ਪੰਜਾਬੀ (pendjabi)',
  'fa': 'فارسی (persan)',
  'ff': 'Fulfulde (peul)',
  'pl': 'polski (polonais)',
  'pt': 'Português (portugais)',
  'qu': 'Runa Simi (quechua)',
  'rm': 'rumantsch grischun (romanche)',
  'ro': 'Română (roumain)',
  'ru': 'Русский (russe)',
  'se': 'Davvisámegiella (same du Nord)',
  'sm': 'gagana fa’a Samoa (samoan)',
  'sg': 'yângâ tî sängö (sango)',
  'sa': 'संस्कृतम् (sanskrit)',
  'sc': 'sardu (sarde)',
  'sr': 'српски језик (serbe)',
  'sn': 'chiShona (shona)',
  'sd': 'सिन्धी (sindhi)',
  'cu': 'ѩзыкъ словѣньскъ (slavon d’église)',
  'sk': 'slovenčina (slovaque)',
  'sl': 'slovenščina (slovène)',
  'so': 'Soomaaliga (somali)',
  'st': 'Sesotho (sotho du Sud)',
  'su': 'Basa Sunda (soundanais)',
  'sv': 'Svenska (suédois)',
  'sw': 'Kiswahili (swahili)',
  'ss': 'SiSwati (swati)',
  'tg': 'тоҷикӣ (tadjik)',
  'tl': 'Wikang Tagalog (tagalog)',
  'ty': 'Reo Tahiti (tahitien)',
  'ta': 'தமிழ் (tamoul)',
  'tt': 'татар теле (tatar)',
  'cs': 'čeština (tchèque)',
  'ce': 'нохчийн мотт (tchétchène)',
  'cv': 'чӑваш чӗлхи (tchouvache)',
  'te': 'తెలుగు (télougou)',
  'th': 'ไทย (thaï)',
  'bo': 'བོད་ཡིག (tibétain)',
  'ti': 'ትግርኛ (tigrigna)',
  'to': 'faka Tonga (tongien)',
  'ts': 'Xitsonga (tsonga)',
  'tn': 'Setswana (tswana)',
  'tr': 'Türkçe (turc)',
  'tk': 'Türkmen (turkmène)',
  'tw': 'Twi',
  'uk': 'Українська (ukrainien)',
  've': 'Tshivenḓa (venda)',
  'vi': 'Tiếng Việt (vietnamien)',
  'vo': 'Volapük',
  'wa': 'walon (wallon)',
  'wo': 'Wollof (wolof)',
  'xh': 'isiXhosa (xhosa)',
  'ii': 'ꆈꌠ꒿ Nuosuhxop (yi du Sichuan)',
  'yi': 'ייִדיש (yiddish)',
  'yo': 'Yorùbá (yoruba)',
  'za': 'Saɯ cueŋƅ (zhuang)',
  'zu': 'isiZulu (zoulou)',
};

/// Paramètres régionaux (langue × pays).
const regionalFormats = <String, String>{
  'fr_FR': 'Français (France)',
  'fr_CM': 'Français (Cameroun)',
  'fr_SN': 'Français (Sénégal)',
  'fr_CI': 'Français (Côte d’Ivoire)',
  'fr_CD': 'Français (RD Congo)',
  'fr_CG': 'Français (Congo)',
  'fr_GA': 'Français (Gabon)',
  'fr_TD': 'Français (Tchad)',
  'fr_CF': 'Français (Centrafrique)',
  'fr_ML': 'Français (Mali)',
  'fr_BF': 'Français (Burkina Faso)',
  'fr_NE': 'Français (Niger)',
  'fr_GN': 'Français (Guinée)',
  'fr_BJ': 'Français (Bénin)',
  'fr_TG': 'Français (Togo)',
  'fr_BI': 'Français (Burundi)',
  'fr_RW': 'Français (Rwanda)',
  'fr_MG': 'Français (Madagascar)',
  'fr_DJ': 'Français (Djibouti)',
  'fr_MR': 'Français (Mauritanie)',
  'fr_HT': 'Français (Haïti)',
  'fr_BE': 'Français (Belgique)',
  'fr_CH': 'Français (Suisse)',
  'fr_CA': 'Français (Canada)',
  'en_US': 'English (United States)',
  'en_GB': 'English (United Kingdom)',
  'en_CM': 'English (Cameroon)',
  'en_NG': 'English (Nigeria)',
  'en_GH': 'English (Ghana)',
  'en_KE': 'English (Kenya)',
  'en_UG': 'English (Uganda)',
  'en_TZ': 'English (Tanzania)',
  'en_ZA': 'English (South Africa)',
  'en_SS': 'English (South Sudan)',
  'en_LR': 'English (Liberia)',
  'en_SL': 'English (Sierra Leone)',
  'en_ZM': 'English (Zambia)',
  'en_ZW': 'English (Zimbabwe)',
  'en_MW': 'English (Malawi)',
  'pt_PT': 'Português (Portugal)',
  'pt_BR': 'Português (Brasil)',
  'pt_MZ': 'Português (Moçambique)',
  'pt_AO': 'Português (Angola)',
  'pt_GW': 'Português (Guiné-Bissau)',
  'es_ES': 'Español (España)',
  'es_GQ': 'Español (Guinea Ecuatorial)',
  'ar_MA': 'العربية (المغرب)',
  'ar_DZ': 'العربية (الجزائر)',
  'ar_TN': 'العربية (تونس)',
  'ar_EG': 'العربية (مصر)',
  'ar_SD': 'العربية (السودان)',
  'ar_TD': 'العربية (تشاد)',
  'sw_KE': 'Kiswahili (Kenya)',
  'sw_TZ': 'Kiswahili (Tanzania)',
  'sw_CD': 'Kiswahili (DRC)',
  'ha_NG': 'Hausa (Nigeria)',
  'yo_NG': 'Yorùbá (Nigeria)',
  'ig_NG': 'Igbo (Nigeria)',
  'am_ET': 'አማርኛ (ኢትዮጵያ)',
  'so_SO': 'Soomaali (Soomaaliya)',
  'rw_RW': 'Ikinyarwanda (Rwanda)',
  'wo_SN': 'Wollof (Senegaal)',
  'ln_CD': 'Lingála (RDC)',
  'mg_MG': 'Malagasy (Madagasikara)',
  'de_DE': 'Deutsch (Deutschland)',
  'it_IT': 'Italiano (Italia)',
  'nl_NL': 'Nederlands (Nederland)',
};
