<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Stocks · {{ $organization->name }} · PharmaCare</title>
<style>
:root{--o:#f47a20;--od:#bd4e08;--ink:#34251d;--muted:#755f53;--line:#eadbd1;--soft:#fff7f0;--danger:#b42318;--green:#18733d}*{box-sizing:border-box}body{margin:0;background:var(--soft);color:var(--ink);font-family:Inter,system-ui,sans-serif}header{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:13px 5%;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:5}.brand{display:flex;align-items:center;gap:11px;color:var(--ink);font-weight:850;text-decoration:none}.brand img{width:46px;height:46px;object-fit:contain}nav{display:flex;gap:16px;flex-wrap:wrap}nav a{color:var(--od);font-weight:750;text-decoration:none}main{max-width:1380px;margin:28px auto;padding:0 20px}.head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.muted{color:var(--muted)}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;margin-bottom:20px;box-shadow:0 12px 34px #7a35000e}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.kpi strong{font-size:28px;color:var(--od)}label{display:block;font-weight:720;font-size:14px;margin:9px 0 5px}input,select,textarea{width:100%;padding:10px 11px;border:1px solid #d8c6bb;border-radius:9px;font:inherit;background:#fff}button,.button{border:0;border-radius:9px;padding:10px 13px;background:var(--o);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.danger{background:var(--danger)}.secondary{background:#fff0e6;color:var(--od)}.message{padding:13px;border-radius:10px;background:#e9f8ee;color:var(--green)}.error{background:#fff0ee;color:var(--danger)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px}.positive{color:var(--green);font-weight:800}.negative,.expiry{color:var(--danger);font-weight:800}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef7f1;color:var(--green);font-size:12px;font-weight:800}@media(max-width:950px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:680px){header{position:static;align-items:flex-start;flex-direction:column}.grid,.kpis{grid-template-columns:1fr}.head{align-items:flex-start}}
</style>
</head>
<body>
<header><a class="brand" href="{{ route('organizations.stocks.index',$organization) }}"><img src="{{ asset('images/pharmacare-logo.png') }}" alt="Logo PharmaCare"><span>PharmaCare · Stocks</span></a><nav><a href="{{ route('organizations.index') }}">Organisations</a><a href="{{ route('organizations.structures.index',$organization) }}">Sites</a><a href="{{ route('organizations.catalog.index',$organization) }}">Produits</a><a href="{{ route('dashboard') }}">Utilisateurs</a></nav></header>
<main>
<div class="head"><div><h1>Stocks et mouvements</h1><p class="muted">{{ $organization->name }} · registre immuable par site et par lot</p></div><form method="get" class="actions"><select name="site_id"><option value="">Tous les sites</option>@foreach($sites as $site)<option value="{{ $site->id }}" @selected(request('site_id')===$site->id)>{{ $site->name }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" placeholder="Produit ou code"><button>Filtrer</button></form></div>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message error">{{ $errors->first() }}</p>@endif
<section class="kpis"><div class="card kpi"><span class="muted">Lignes de stock</span><br><strong>{{ $balances->total() }}</strong></div><div class="card kpi"><span class="muted">Quantité visible</span><br><strong>{{ number_format($balances->sum('theoretical_quantity'),2,',',' ') }}</strong></div><div class="card kpi"><span class="muted">Lots proches de péremption</span><br><strong>{{ $balances->filter(fn($b)=>$b->batch->expires_on?->lte(now()->addMonths(3)))->count() }}</strong></div></section>

@if(auth()->user()->hasPermission('stocks.manage'))
<section class="card"><h2>Enregistrer un mouvement</h2><p class="muted">Les mouvements validés ne sont jamais modifiés ou supprimés. Une erreur doit être corrigée par compensation.</p>
<form method="post" action="{{ route('organizations.stocks.movements.store',$organization) }}">@csrf<div class="grid">
<div><label>Site</label><select name="site_id" required>@foreach($sites as $site)<option value="{{ $site->id }}">{{ $site->name }} · {{ $site->healthFacility->name }}</option>@endforeach</select></div>
<div><label>Produit et lot</label><select name="batch_id" required>@foreach($products as $product)@foreach($product->batches as $batch)<option value="{{ $batch->id }}">{{ $product->name }} · {{ $batch->batch_number }} · exp. {{ $batch->expires_on->format('d/m/Y') }}</option>@endforeach @endforeach</select></div>
<div><label>Type</label><select name="movement_type">@foreach(['opening'=>'Stock initial','receipt'=>'Réception','entry'=>'Autre entrée','issue'=>'Sortie','return_in'=>'Retour entrant','return_out'=>'Retour sortant','adjustment_in'=>'Ajustement positif','adjustment_out'=>'Ajustement négatif','loss'=>'Perte','damage'=>'Détérioration','expiry'=>'Péremption','quarantine'=>'Mise en quarantaine','quarantine_release'=>'Sortie de quarantaine','destruction'=>'Destruction'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
<div><label>Quantité</label><input type="number" name="quantity" min="0.0001" step="0.0001" required></div><div style="grid-column:span 4"><label>Justification</label><textarea name="reason" placeholder="Obligatoire pour ajustement, perte, détérioration, péremption, quarantaine ou destruction"></textarea></div></div><p><button>Valider le mouvement</button></p></form></section>
@endif

<section class="card"><h2>Soldes par site, produit et lot</h2><div class="table-wrap"><table><thead><tr><th>Site</th><th>Produit</th><th>Lot</th><th>Expiration</th><th>Théorique</th><th>Physique</th><th>Réservé</th><th>Disponible</th></tr></thead><tbody>
@forelse($balances as $balance)<tr><td>{{ $balance->site->name }}</td><td><strong>{{ $balance->product->name }}</strong><br><span class="muted">{{ $balance->product->code }}</span></td><td>{{ $balance->batch->batch_number }}</td><td class="{{ $balance->batch->expires_on?->lte(now()->addMonths(3))?'expiry':'' }}">{{ $balance->batch->expires_on?->format('d/m/Y') }}</td><td>{{ $balance->theoretical_quantity }}</td><td>{{ $balance->physical_quantity ?? '—' }}</td><td>{{ $balance->reserved_quantity }}</td><td><span class="badge">{{ $balance->available_quantity }}</span></td></tr>@empty<tr><td colspan="8">Aucun stock enregistré. Utilisez « Stock initial » ou « Réception ».</td></tr>@endforelse
</tbody></table></div>{{ $balances->links() }}</section>

<section class="card"><h2>Registre des mouvements récents</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Site</th><th>Produit / lot</th><th>Type</th><th>Quantité</th><th>Justification / correction</th></tr></thead><tbody>
@forelse($movements as $movement)<tr><td>{{ $movement->validated_at?->format('d/m/Y H:i') }}</td><td>{{ $movement->site->name }}</td><td>{{ $movement->product->name }}<br><span class="muted">{{ $movement->batch->batch_number }}</span></td><td>{{ $movement->movement_type }}</td><td class="{{ (float)$movement->quantity>=0?'positive':'negative' }}">{{ (float)$movement->quantity>=0?'+':'' }}{{ $movement->quantity }}</td><td>{{ $movement->reason }}@if(!$movement->compensates_movement_id && auth()->user()->hasPermission('stocks.adjust'))<form class="actions" method="post" action="{{ route('organizations.stocks.movements.compensate',[$organization,$movement]) }}" onsubmit="return confirm('Créer un mouvement compensatoire ? Le mouvement original restera visible.')">@csrf<input name="reason" required minlength="5" placeholder="Motif de correction"><button class="danger">Compenser</button></form>@elseif($movement->compensates_movement_id)<span class="badge">Compensation</span>@endif</td></tr>@empty<tr><td colspan="6">Aucun mouvement.</td></tr>@endforelse
</tbody></table></div></section>
</main></body></html>
