<?php
namespace Tests\Feature\Api;
use App\Models\Batch; use App\Models\HealthFacility; use App\Models\Organization; use App\Models\Permission; use App\Models\Product; use App\Models\Role; use App\Models\Site; use App\Models\StockBalance; use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class InventoryManagementTest extends TestCase {
 use RefreshDatabase;
 private function context():array{$o=Organization::create(['code'=>'INV','name'=>'Organisation inventaire']);$f=HealthFacility::create(['organization_id'=>$o->id,'code'=>'F','name'=>'Centre','facility_type'=>'clinic']);$s=Site::create(['organization_id'=>$o->id,'health_facility_id'=>$f->id,'code'=>'S','name'=>'Pharmacie','site_type'=>'stock_and_dispensing']);$p=Product::create(['organization_id'=>$o->id,'code'=>'P','name'=>'Produit','product_type'=>'medicine']);$b=Batch::create(['organization_id'=>$o->id,'product_id'=>$p->id,'batch_number'=>'LOT-1','expires_on'=>now()->addYear(),'unit_cost'=>100,'status'=>'available']);StockBalance::create(['organization_id'=>$o->id,'site_id'=>$s->id,'product_id'=>$p->id,'batch_id'=>$b->id,'theoretical_quantity'=>10,'reserved_quantity'=>0]);$permissions=collect(['inventories.view','inventories.manage','inventories.validate','stocks.manage'])->map(fn($c)=>Permission::firstOrCreate(['code'=>$c],['name'=>$c]));$role=Role::create(['code'=>'inventory_test','name'=>'Inventaire']);$role->permissions()->attach($permissions);$u=User::factory()->create(['is_active'=>true,'organization_id'=>$o->id]);$u->roles()->attach($role,['scope_type'=>'organization','scope_id'=>$o->id]);Sanctum::actingAs($u);return compact('o','s','p','b','u');}
 public function test_complete_inventory_freeze_count_variance_and_adjustment_cycle():void{$c=$this->context();$uuid=fake()->uuid();$payload=['offline_uuid'=>$uuid,'site_id'=>$c['s']->id,'reference'=>'INV-001','inventory_type'=>'monthly','period_date'=>today()->toDateString()];$inventory=$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories",$payload)->assertCreated()->json('inventory');$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories",$payload)->assertOk()->assertJsonPath('inventory.id',$inventory['id']);$started=$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inventory['id']}/start")->assertOk()->assertJsonPath('inventory.status','counting')->json('inventory');$this->postJson("/api/v1/organizations/{$c['o']->id}/stocks/movements",['site_id'=>$c['s']->id,'batch_id'=>$c['b']->id,'movement_type'=>'issue','quantity'=>1])->assertStatus(423);$line=$started['lines'][0];$this->putJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inventory['id']}/count",['lines'=>[['id'=>$line['id'],'physical_quantity'=>8]]])->assertUnprocessable();$this->putJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inventory['id']}/count",['lines'=>[['id'=>$line['id'],'physical_quantity'=>8,'justification'=>'Deux unités détériorées constatées']]])->assertOk()->assertJsonPath('inventory.lines.0.variance_quantity','-2.0000');$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inventory['id']}/submit")->assertOk()->assertJsonPath('inventory.status','submitted');$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inventory['id']}/validate",['decision'=>'approve'])->assertOk()->assertJsonPath('inventory.status','validated')->assertJsonPath('inventory.variance_value','-200.0000');$this->assertDatabaseHas('stock_balances',['batch_id'=>$c['b']->id,'theoretical_quantity'=>8,'physical_quantity'=>8]);$this->assertDatabaseHas('stock_movements',['movement_type'=>'adjustment_out','reference_type'=>'inventory','reference_id'=>$inventory['id']]);$this->assertDatabaseHas('audit_logs',['event'=>'inventory.validated']);
 $this->assertDatabaseHas('notifications', ['notifiable_id'=>$c['u']->id]);
 $this->actingAs($c['u'], 'web');
 $center=$this->getJson('/profile/notifications')->assertOk()->assertJsonPath('unread_count',1)->assertJsonPath('data.0.title','Inventaire validé');
 $this->get('/dashboard')->assertOk()->assertSee('data-notification-count', false);
 $this->postJson('/profile/notifications/'.$center->json('data.0.id').'/read')->assertOk()->assertJsonPath('unread_count',0);
 $this->getJson('/profile/notifications')->assertJsonPath('data.0.read',true);
}
 public function test_inventory_rejection_keeps_stock_unchanged():void{$c=$this->context();$inv=$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories",['site_id'=>$c['s']->id,'reference'=>'INV-R','inventory_type'=>'exceptional','period_date'=>today()->toDateString()])->assertCreated()->json('inventory');$started=$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inv['id']}/start")->json('inventory');$this->putJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inv['id']}/count",['lines'=>[['id'=>$started['lines'][0]['id'],'physical_quantity'=>10]]])->assertOk();$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inv['id']}/submit")->assertOk();$this->postJson("/api/v1/organizations/{$c['o']->id}/inventories/{$inv['id']}/validate",['decision'=>'reject','rejection_reason'=>'Comptage témoin à reprendre'])->assertOk()->assertJsonPath('inventory.status','rejected');$this->assertDatabaseHas('stock_balances',['batch_id'=>$c['b']->id,'theoretical_quantity'=>10]);}
}
