<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Organisations · SAGASTOCK</title>
<style>:root{--o:#f47a20;--s:#fff7f0;--d:#382319}*{box-sizing:border-box}body{margin:0;font-family:system-ui;background:var(--s);color:var(--d)}header{background:var(--o);padding:18px 5%;color:#fff;display:flex;gap:20px}header a{color:#fff}main{max-width:1250px;margin:auto;padding:28px 5%}.card{background:#fff;padding:22px;border-radius:16px;margin-bottom:22px;box-shadow:0 10px 30px #7a350015}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}input,textarea{width:100%;padding:11px;border:1px solid #dbcabd;border-radius:9px;font:inherit}textarea{min-height:70px}.wide{grid-column:span 2}button{background:var(--o);color:#fff;border:0;padding:11px 15px;border-radius:9px;font-weight:700}.danger{background:#b42318}.message{background:#eaf8ef;color:#176b3a;padding:13px;border-radius:9px}.item{border-top:1px solid #f1e1d5;padding:20px 0}.head{display:flex;justify-content:space-between;gap:15px;align-items:center}.muted{color:#78665a}.search{display:flex;gap:8px}@media(max-width:800px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.head,.search{display:block}.search input{margin-bottom:8px}}</style></head>
<body><header><strong>SAGASTOCK · Organisations</strong><a href="{{ route('dashboard') }}">Utilisateurs</a><a href="{{ route('security.index') }}">Sécurité</a><a href="{{ route('profile.show') }}">Mon profil</a></header><main>
<h1>Organisations / ONG</h1><p class="muted">Premier niveau de la hiérarchie opérationnelle SAGASTOCK.</p>
@if(session('status'))<p class="message">{{ session('status') }}</p>@endif @if($errors->any())<p class="message">{{ $errors->first() }}</p>@endif
<section class="card"><h2>Nouvelle organisation</h2><form method="post" action="{{ route('organizations.store') }}">@csrf
<div class="grid"><input name="code" value="{{ old('code') }}" placeholder="Code unique (ex. ONG_CM)" required><input name="name" value="{{ old('name') }}" placeholder="Nom usuel" required><input name="legal_name" value="{{ old('legal_name') }}" placeholder="Raison sociale"><input name="email" type="email" value="{{ old('email') }}" placeholder="Adresse e-mail"><input name="phone" value="{{ old('phone') }}" placeholder="Téléphone"><input name="country_code" maxlength="2" value="{{ old('country_code') }}" placeholder="Pays (CM, FR...)"><textarea class="wide" name="address" placeholder="Adresse">{{ old('address') }}</textarea><label><input style="width:auto" type="checkbox" name="is_active" value="1" checked> Organisation active</label></div><p><button>Créer l’organisation</button></p></form></section>
<section class="card"><div class="head"><h2>Organisations existantes</h2><form class="search" method="get"><input name="search" value="{{ request('search') }}" placeholder="Nom ou code"><button>Rechercher</button></form></div>
@forelse($organizations as $organization)<article class="item"><form method="post" action="{{ route('organizations.update',$organization) }}">@csrf @method('PUT')
<div class="head"><div><strong>{{ $organization->name }}</strong><div class="muted">{{ $organization->code }}</div></div><div><label><input style="width:auto" type="checkbox" name="is_active" value="1" @checked($organization->is_active)> Active</label> <button>Enregistrer</button></div></div>
<div class="grid" style="margin-top:14px"><input name="code" value="{{ $organization->code }}" required><input name="name" value="{{ $organization->name }}" required><input name="legal_name" value="{{ $organization->legal_name }}" placeholder="Raison sociale"><input name="email" type="email" value="{{ $organization->email }}" placeholder="E-mail"><input name="phone" value="{{ $organization->phone }}" placeholder="Téléphone"><input name="country_code" maxlength="2" value="{{ $organization->country_code }}" placeholder="Pays"><textarea class="wide" name="address" placeholder="Adresse">{{ $organization->address }}</textarea></div></form>
<form method="post" action="{{ route('organizations.destroy',$organization) }}" onsubmit="return confirm('Archiver cette organisation ?')">@csrf @method('DELETE')<button class="danger">Archiver</button></form></article>
@empty<p>Aucune organisation enregistrée.</p>@endforelse {{ $organizations->withQueryString()->links() }}</section></main></body></html>
